import { createScheduleAction } from "../../actions";
import { getTreasuryOptions } from "@/lib/treasury";
import { requireTreasuryContext } from "@/lib/treasury-access";
import { Header, inputClass, Notice } from "../../treasury-ui";

export default async function Page({ searchParams }: { searchParams: Promise<{ direction?: string; error?: string }> }) {
  const query = await searchParams; const direction = query.direction === "PAYABLE" ? "PAYABLE" : "RECEIVABLE"; const { companyId, locationId } = await requireTreasuryContext(direction === "RECEIVABLE" ? "receipt" : "payment"); const options = await getTreasuryOptions(companyId, locationId); const partners = options.partners.filter(p => direction === "RECEIVABLE" ? p.isCustomer : p.isSupplier);
  return <><Header title={direction === "RECEIVABLE" ? "Nuova scadenza cliente" : "Nuova scadenza fornitore"} subtitle="Inserimento manuale autorizzato e tenant-scoped." /><Notice error={query.error} /><form action={createScheduleAction} className="grid gap-4 rounded border bg-white p-6 md:grid-cols-2"><input name="direction" type="hidden" value={direction} /><label>Partner<select className={inputClass} name="partnerId" required><option value="">Seleziona</option>{partners.map(p => <option key={p.id} value={p.id}>{p.displayName ?? p.name}</option>)}</select></label><label>Scadenza<input className={inputClass} name="dueDate" type="date" required /></label><label>Importo<input className={inputClass} min="0.01" name="amount" step="0.01" type="number" required /></label><label>Valuta<input className={inputClass} defaultValue="EUR" maxLength={3} name="currency" required /></label><label>Metodo di pagamento<select className={inputClass} name="paymentMethodId"><option value="">Nessuno</option>{options.paymentMethods.map(v => <option key={v.id} value={v.id}>{v.code} · {v.name}</option>)}</select></label><label>Condizione di pagamento<select className={inputClass} name="paymentTermId"><option value="">Nessuna</option>{options.paymentTerms.map(v => <option key={v.id} value={v.id}>{v.code} · {v.name}</option>)}</select></label><label className="md:col-span-2">Note<textarea className={inputClass} name="notes" /></label><button className="rounded bg-slate-900 px-4 py-2 text-white md:col-span-2">Crea scadenza</button></form></>;
}
