"use server";
import { redirect } from "next/navigation";
import { requireTreasuryContext } from "@/lib/treasury-access";
import { beginConnection, linkAccount, refreshConnection, revokeConnection, syncConnection } from "@/lib/open-banking/service";
import { resolveOpenBankingCallbackUrl } from "@/lib/open-banking/config";
const value = (data: FormData, key: string) => String(data.get(key) ?? "").trim();
const destination = (kind: "success" | "error", message: string) => `/treasury/open-banking?${kind}=${encodeURIComponent(message)}`;
export async function connectBankAction(data: FormData) { const { companyId, locationId } = await requireTreasuryContext("manage"); let target: string; try { const callback = resolveOpenBankingCallbackUrl(); if (!callback.valid) throw new Error(callback.error); const row = await beginConnection(companyId, locationId, value(data, "institutionId"), callback.url); target = row.authorizationUrl; } catch (error) { target = destination("error", error instanceof Error ? error.message : "Operazione non riuscita."); } redirect(target); }
export async function syncBankAction(data: FormData) { const { companyId } = await requireTreasuryContext("reconcile"); let target: string; try { await syncConnection(companyId, value(data, "connectionId")); target = destination("success", "Sincronizzazione completata."); } catch (error) { target = destination("error", error instanceof Error ? error.message : "Sincronizzazione non riuscita."); } redirect(target); }
export async function refreshBankAction(data: FormData) { const { companyId } = await requireTreasuryContext("manage"); let target: string; try { await refreshConnection(companyId, value(data, "connectionId")); target = destination("success", "Consenso rinnovato."); } catch (error) { target = destination("error", error instanceof Error ? error.message : "Rinnovo non riuscito."); } redirect(target); }
export async function revokeBankAction(data: FormData) { const { companyId } = await requireTreasuryContext("manage"); let target: string; try { await revokeConnection(companyId, value(data, "connectionId")); target = destination("success", "Connessione revocata."); } catch (error) { target = destination("error", error instanceof Error ? error.message : "Revoca non riuscita."); } redirect(target); }
export async function linkBankAccountAction(data: FormData) { const { companyId, locationId } = await requireTreasuryContext("manage"); let target: string; try { await linkAccount(companyId, locationId, value(data, "openBankingAccountId"), value(data, "financialAccountId")); target = destination("success", "Conto finanziario collegato."); } catch (error) { target = destination("error", error instanceof Error ? error.message : "Collegamento non riuscito."); } redirect(target); }
