"use server";
import { cancelDocument, closeDocument, confirmDocument, createDraft, DocumentDomainError, duplicateDraft, postDocument, updateDraft } from "@/lib/documents";
import { requireDocumentContext } from "@/lib/document-access";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";

const text = (data: FormData, key: string) => String(data.get(key) ?? "").trim() || null;
const number = (data: FormData, key: string, fallback = 0) => { const parsed = Number(String(data.get(key) ?? "").replace(",", ".")); return Number.isFinite(parsed) ? parsed : fallback; };
function input(data: FormData) { return { seriesId: text(data, "seriesId")!, partnerId: text(data, "partnerId")!, documentDate: new Date(text(data, "documentDate") ?? new Date()), currency: text(data, "currency") ?? "EUR", exchangeRate: number(data, "exchangeRate", 1), warehouseId: text(data, "warehouseId"), locationId: text(data, "locationId"), paymentMethodId: text(data, "paymentMethodId"), paymentTermId: text(data, "paymentTermId"), priceListId: text(data, "priceListId"), notes: text(data, "notes"), internalNotes: text(data, "internalNotes"), lines: [{ itemId: text(data, "itemId")!, description: text(data, "description"), quantity: number(data, "quantity"), unitOfMeasureId: text(data, "unitOfMeasureId")!, unitPrice: number(data, "unitPrice"), discount: number(data, "lineDiscount"), vatRateId: text(data, "vatRateId")!, warehouseId: text(data, "lineWarehouseId"), lotId: text(data, "lotId"), serialId: text(data, "serialId"), notes: text(data, "lineNotes") }] }; }
const message = (error: unknown) => encodeURIComponent(error instanceof DocumentDomainError || error instanceof Error ? error.message : "Operazione non riuscita.");
export async function saveDocumentAction(data: FormData) { const { companyId, userId } = await requireDocumentContext(true); const id = text(data, "id"); let result: { id: string }; try { const parsed = input(data); result = id ? await updateDraft(companyId, userId, id, parsed) : await createDraft(companyId, userId, parsed); } catch (error) { redirect(`${id ? `/documents/${id}/edit` : "/documents/new"}?error=${message(error)}`); } revalidatePath("/documents"); redirect(`/documents/${result.id}`); }
export async function transitionDocumentAction(data: FormData) { const { companyId, userId } = await requireDocumentContext(true); const id = text(data, "id")!; const operation = text(data, "operation"); let destination = `/documents/${id}?success=Stato aggiornato`; try { if (operation === "confirm") await confirmDocument(companyId, userId, id); else if (operation === "post") await postDocument(companyId, userId, id); else if (operation === "close") await closeDocument(companyId, userId, id); else if (operation === "cancel") await cancelDocument(companyId, userId, id); else if (operation === "duplicate") { const copy = await duplicateDraft(companyId, userId, id); destination = `/documents/${copy.id}/edit`; } } catch (error) { redirect(`/documents/${id}?error=${message(error)}`); } revalidatePath("/documents"); redirect(destination); }
