import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { after, before, test } from "node:test";
import { CRM_CAPABILITIES, CrmAccessDeniedError, assertCrmCapability, type CrmActor } from "../../lib/crm-access";
import { archiveCrmOpportunity, createCrmActivity, createCrmOpportunity, createCrmPipeline, getCrmActivities, getCrmDashboard, getCrmOpportunities, getCrmOpportunity, getCrmPipelines, getPartnerCrmSummary, getCrmTimeline, moveCrmOpportunityStage, setCrmActivityStatus, updateCrmActivity, updateCrmOpportunity, crmNewOpportunityHref, crmOpportunityHref } from "../../lib/crm";
import { prisma } from "../../lib/prisma";

const databaseName = new URL(process.env.DATABASE_URL ?? "postgresql://invalid/invalid").pathname.slice(1);
if (!databaseName.endsWith("_test")) throw new Error("CRM Phase 2 richiede un database con suffisso _test.");

const ids = { company:"", foreignCompany:"", manager:"", sales:"", sales2:"", accountant:"", warehouse:"", foreignManager:"", partner:"", partner2:"", foreignPartner:"", location:"", foreignLocation:"", pipeline:"", foreignPipeline:"", secondPipeline:"", secondOpen:"", open:"", proposal:"", won:"", lost:"", opportunity:"", otherOpportunity:"", foreignOpportunity:"", activity:"" };
const actor = (membershipId:string, roles:string[], companyId=ids.company):CrmActor => ({companyId,membershipId,userId:membershipId,roles});
const manager=()=>actor(ids.manager,["MANAGER"]), sales=()=>actor(ids.sales,["SALES"]), sales2=()=>actor(ids.sales2,["SALES"]), accountant=()=>actor(ids.accountant,["ACCOUNTANT"]), warehouse=()=>actor(ids.warehouse,["WAREHOUSE"]), foreign=()=>actor(ids.foreignManager,["MANAGER"],ids.foreignCompany);

before(async()=>{
  const suffix=randomUUID().slice(0,8);
  const c=await prisma.company.create({data:{name:`CRM2 ${suffix}`}}); const fc=await prisma.company.create({data:{name:`CRM2 foreign ${suffix}`}}); ids.company=c.id;ids.foreignCompany=fc.id;
  async function member(companyId:string,label:string){const u=await prisma.user.create({data:{firstName:label,lastName:"CRM",email:`${label}.${suffix}@test.invalid`,password:"test"}});return (await prisma.membership.create({data:{companyId,userId:u.id}})).id}
  ids.manager=await member(ids.company,"manager");ids.sales=await member(ids.company,"sales");ids.sales2=await member(ids.company,"sales2");ids.accountant=await member(ids.company,"accountant");ids.warehouse=await member(ids.company,"warehouse");ids.foreignManager=await member(ids.foreignCompany,"foreign");
  ids.location=(await prisma.location.create({data:{companyId:ids.company,code:`L-${suffix}`,name:"CRM Location"}})).id;ids.foreignLocation=(await prisma.location.create({data:{companyId:ids.foreignCompany,code:`F-${suffix}`,name:"Foreign Location"}})).id;
  ids.partner=(await prisma.partner.create({data:{companyId:ids.company,code:`P-${suffix}`,name:"CRM Customer",isCustomer:true}})).id;ids.partner2=(await prisma.partner.create({data:{companyId:ids.company,code:`P2-${suffix}`,name:"CRM Customer 2",isCustomer:true}})).id;ids.foreignPartner=(await prisma.partner.create({data:{companyId:ids.foreignCompany,code:`FP-${suffix}`,name:"Foreign Customer",isCustomer:true}})).id;
});

after(async()=>{if(ids.company)await prisma.company.deleteMany({where:{id:{in:[ids.company,ids.foreignCompany]}}});await prisma.user.deleteMany({where:{email:{endsWith:"@test.invalid"},memberships:{none:{}}}});await prisma.$disconnect()});

test("01 manager crea pipeline e stage iniziali",async()=>{ids.pipeline=(await createCrmPipeline(manager(),{name:"Vendite",isDefault:true})).id;const p=await getCrmPipelines(manager());assert.equal(p.length,1);const stages=p[0].stages as Array<{id:string;code:string}>;ids.open=stages.find(s=>s.code==="QUALIFICATION")!.id;ids.proposal=stages.find(s=>s.code==="PROPOSAL")!.id;ids.won=stages.find(s=>s.code==="WON")!.id;ids.lost=stages.find(s=>s.code==="LOST")!.id;assert.equal(stages.length,4)});
test("02 pipeline Company B isolata",async()=>{ids.foreignPipeline=(await createCrmPipeline(foreign(),{name:"Foreign"})).id;assert.equal((await getCrmPipelines(manager())).some(p=>p.id===ids.foreignPipeline),false);assert.equal((await getCrmPipelines(foreign())).length,1);const fp=await getCrmPipelines(foreign());const fs=(fp[0].stages as Array<{id:string;code:string}>).find(s=>s.code==="QUALIFICATION")!;ids.foreignOpportunity=(await createCrmOpportunity(foreign(),{partnerId:ids.foreignPartner,pipelineId:ids.foreignPipeline,stageId:fs.id,title:"Foreign opportunity"})).id});
test("03 sales non amministra pipeline",()=>assert.rejects(()=>createCrmPipeline(sales(),{name:"No"}),CrmAccessDeniedError));
test("04 warehouse non legge CRM",()=>assert.throws(()=>assertCrmCapability(warehouse().roles,CRM_CAPABILITIES.READ),CrmAccessDeniedError));
test("05 manager crea opportunità assegnata sales",async()=>{ids.opportunity=(await createCrmOpportunity(manager(),{partnerId:ids.partner,pipelineId:ids.pipeline,stageId:ids.open,ownerMembershipId:ids.sales,locationId:ids.location,title:"Contratto annuale",estimatedValue:"1000.00",probability:25,expectedCloseDate:new Date("2026-09-30T00:00:00.000Z")})).id;assert.ok(ids.opportunity)});
test("05a Partner 360 genera URL completi",()=>{assert.equal(crmOpportunityHref(ids.opportunity),`/crm/opportunities/${ids.opportunity}`);assert.equal(crmNewOpportunityHref(ids.partner),`/crm/opportunities/new?partnerId=${ids.partner}`);assert.throws(()=>crmOpportunityHref(""));assert.throws(()=>crmNewOpportunityHref(""))});
test("06 sales crea solo opportunità propria",async()=>{ids.otherOpportunity=(await createCrmOpportunity(sales2(),{partnerId:ids.partner,pipelineId:ids.pipeline,stageId:ids.open,title:"Sales 2",estimatedValue:"200"})).id;await assert.rejects(()=>createCrmOpportunity(sales(),{partnerId:ids.partner,pipelineId:ids.pipeline,stageId:ids.open,ownerMembershipId:ids.sales2,title:"No assign"}),CrmAccessDeniedError)});
test("07 accountant è read-only",()=>assert.rejects(()=>createCrmOpportunity(accountant(),{partnerId:ids.partner,pipelineId:ids.pipeline,stageId:ids.open,title:"No write"}),CrmAccessDeniedError));
test("08 manager vede tutte le opportunità",async()=>assert.equal((await getCrmOpportunities(manager())).length,2));
test("09 sales vede solo le proprie",async()=>{const rows=await getCrmOpportunities(sales());assert.equal(rows.length,1);assert.equal(rows[0].ownerMembershipId,ids.sales)});
test("10 accountant vede tutte le opportunità",async()=>assert.equal((await getCrmOpportunities(accountant())).length,2));
test("11 cross-company read è rifiutata",async()=>assert.equal(await getCrmOpportunity(foreign(),ids.opportunity),null));
test("12 cross-company partner è rifiutato",()=>assert.rejects(()=>createCrmOpportunity(manager(),{partnerId:ids.foreignPartner,pipelineId:ids.pipeline,stageId:ids.open,title:"Foreign"}),/Riferimento CRM/));
test("13 cross-company location è rifiutata",()=>assert.rejects(()=>createCrmOpportunity(manager(),{partnerId:ids.partner,pipelineId:ids.pipeline,stageId:ids.open,locationId:ids.foreignLocation,title:"Foreign loc"}),/Riferimento CRM/));
test("14 owner cross-company e stage cross-pipeline rifiutati",async()=>{await assert.rejects(()=>createCrmOpportunity(manager(),{partnerId:ids.partner,pipelineId:ids.pipeline,stageId:ids.open,ownerMembershipId:ids.foreignManager,title:"Foreign owner"}),/Riferimento CRM/);ids.secondPipeline=(await createCrmPipeline(manager(),{name:"Altra pipeline"})).id;const other=(await getCrmPipelines(manager())).find(p=>p.id===ids.secondPipeline)!;ids.secondOpen=(other.stages as Array<{id:string;code:string}>).find(s=>s.code==="QUALIFICATION")!.id;await assert.rejects(()=>createCrmOpportunity(manager(),{partnerId:ids.partner,pipelineId:ids.pipeline,stageId:ids.secondOpen,title:"Stage mismatch"}),/Riferimento CRM/)});
test("15 sales aggiorna la propria opportunità",async()=>{await updateCrmOpportunity(sales(),ids.opportunity,{title:"Contratto aggiornato",estimatedValue:"1250.50",currency:"EUR",probability:40,locationId:ids.location});assert.equal((await getCrmOpportunity(sales(),ids.opportunity))?.title,"Contratto aggiornato")});
test("15a edit invariato preserva tutti i riferimenti",async()=>{const before=await getCrmOpportunity(sales(),ids.opportunity);await updateCrmOpportunity(sales(),ids.opportunity,{partnerId:before!.partnerId,pipelineId:before!.pipelineId,stageId:before!.stageId,ownerMembershipId:before!.ownerMembershipId,locationId:before!.locationId,expectedCloseDate:before!.expectedCloseDate,title:before!.title,description:before!.description||undefined,source:before!.source||undefined,estimatedValue:before!.estimatedValue,currency:before!.currency,probability:before!.probability,lostReason:before!.lostReason});const after=await getCrmOpportunity(sales(),ids.opportunity);for(const key of ["partnerId","pipelineId","stageId","ownerMembershipId","locationId"] as const)assert.equal(after![key],before![key]);assert.equal(after!.expectedCloseDate?.toISOString(),before!.expectedCloseDate?.toISOString())});
test("15b edit solo titolo preserva riferimenti e data",async()=>{const before=await getCrmOpportunity(sales(),ids.opportunity);await updateCrmOpportunity(sales(),ids.opportunity,{partnerId:before!.partnerId,pipelineId:before!.pipelineId,stageId:before!.stageId,ownerMembershipId:before!.ownerMembershipId,locationId:before!.locationId,expectedCloseDate:before!.expectedCloseDate,title:"Solo titolo",estimatedValue:before!.estimatedValue,currency:before!.currency,probability:before!.probability});const after=await getCrmOpportunity(sales(),ids.opportunity);assert.equal(after!.title,"Solo titolo");for(const key of ["partnerId","pipelineId","stageId","ownerMembershipId","locationId"] as const)assert.equal(after![key],before![key]);assert.equal(after!.expectedCloseDate?.toISOString(),before!.expectedCloseDate?.toISOString())});
test("15c cambio pipeline richiede stage coerente",()=>assert.rejects(()=>updateCrmOpportunity(sales(),ids.opportunity,{pipelineId:ids.secondPipeline,stageId:ids.open,title:"Mismatch",estimatedValue:"1",currency:"EUR",probability:1}),/Riferimento CRM/));
test("16 sales non aggiorna opportunità altrui",()=>assert.rejects(()=>updateCrmOpportunity(sales(),ids.otherOpportunity,{title:"No",estimatedValue:"1",currency:"EUR",probability:1}),/non accessibile/));
test("17 cambio stage aggiorna probabilità",async()=>{await moveCrmOpportunityStage(sales(),ids.opportunity,ids.proposal);assert.equal((await getCrmOpportunity(sales(),ids.opportunity))?.probability,50)});
test("18 won valorizza wonAt",async()=>{await moveCrmOpportunityStage(sales(),ids.opportunity,ids.won);const row=await getCrmOpportunity(sales(),ids.opportunity);assert.ok(row?.wonAt);assert.equal(row?.lostAt,null)});
test("19 reopen pulisce stato terminale",async()=>{await moveCrmOpportunityStage(sales(),ids.opportunity,ids.open);const row=await getCrmOpportunity(sales(),ids.opportunity);assert.equal(row?.wonAt,null);assert.equal(row?.stageType,"OPEN")});
test("20 lost richiede motivo",()=>assert.rejects(()=>moveCrmOpportunityStage(sales(),ids.opportunity,ids.lost),/Motivo perdita/));
test("21 lost salva motivo",async()=>{await moveCrmOpportunityStage(sales(),ids.opportunity,ids.lost,"Budget");assert.equal((await getCrmOpportunity(sales(),ids.opportunity))?.lostReason,"Budget")});
test("22 Activity Partner, Opportunity e overdue persistenti",async()=>{ids.activity=(await createCrmActivity(sales(),{opportunityId:ids.opportunity,type:"FOLLOW_UP",subject:"Richiamare",dueAt:new Date(Date.now()+86400000),priority:"HIGH"})).id;await createCrmActivity(manager(),{partnerId:ids.partner,type:"CALL",subject:"Scaduta",dueAt:new Date(Date.now()-86400000),assignedMembershipId:ids.sales});assert.equal((await getCrmActivities(sales(),{opportunityId:ids.opportunity})).length,1);assert.ok((await getCrmActivities(sales(),{partnerId:ids.partner})).length>=2)});
test("23 assignee non autorizzato e cross-company rifiutati",async()=>{await assert.rejects(()=>createCrmActivity(sales(),{partnerId:ids.partner,assignedMembershipId:ids.sales2,type:"CALL",subject:"No"}),CrmAccessDeniedError);await assert.rejects(()=>createCrmActivity(manager(),{partnerId:ids.partner,assignedMembershipId:ids.foreignManager,type:"CALL",subject:"Foreign"}),/Riferimento attività/)});
test("23a Activity Opportunity e Partner coerenti",async()=>{const valid=await createCrmActivity(sales(),{opportunityId:ids.opportunity,partnerId:ids.partner,type:"CALL",subject:"Coerente"});const derived=await createCrmActivity(sales(),{opportunityId:ids.opportunity,type:"CALL",subject:"Derivata"});const rows=await getCrmActivities(sales(),{opportunityId:ids.opportunity});assert.equal(rows.find(r=>r.id===valid.id)?.partnerId,ids.partner);assert.equal(rows.find(r=>r.id===derived.id)?.partnerId,ids.partner);await assert.rejects(()=>createCrmActivity(sales(),{opportunityId:ids.opportunity,partnerId:ids.partner2,type:"CALL",subject:"Incoerente"}),/non coincide/);await assert.rejects(()=>createCrmActivity(manager(),{opportunityId:ids.foreignOpportunity,type:"CALL",subject:"Cross company"}),/non accessibile/);await prisma.$executeRaw`DELETE FROM "CrmOpportunity" WHERE "companyId" = ${ids.foreignCompany} AND "id" = ${ids.foreignOpportunity}`;ids.foreignOpportunity=""});
test("23b update Activity incoerente rifiutato",async()=>{await assert.rejects(()=>updateCrmActivity(sales(),ids.activity,{partnerId:ids.partner2}),/non coincide/);await updateCrmActivity(sales(),ids.activity,{partnerId:ids.partner});assert.equal((await getCrmActivities(sales(),{opportunityId:ids.opportunity})).find(r=>r.id===ids.activity)?.partnerId,ids.partner)});
test("24 completamento attività registra data",async()=>{await setCrmActivityStatus(sales(),ids.activity,"COMPLETED");const row=(await getCrmActivities(sales(),{opportunityId:ids.opportunity}))[0];assert.equal(row.status,"COMPLETED");assert.ok(row.completedAt)});
test("25 timeline contiene eventi lifecycle e activity",async()=>{const rows=await getCrmTimeline(sales(),{opportunityId:ids.opportunity});assert.ok(rows.some(e=>e.eventType==="OPPORTUNITY_REOPENED"));assert.ok(rows.some(e=>e.eventType==="ACTIVITY_COMPLETED"))});
test("26 dashboard weighted, conversion, overdue e tenant isolation",async()=>{const data=await getCrmDashboard(manager());const partner=await getPartnerCrmSummary(sales(),ids.partner);const isolated=await getCrmDashboard(foreign());assert.equal(data.summary.pipelineValue,"200.00");assert.equal(data.summary.weightedValue,"20.0000000000000000");assert.equal(data.summary.conversionRate,"0.00");assert.ok(data.activities.overdue>=1);assert.equal(typeof partner.openValue,"string");assert.equal(isolated.summary.openCount,0)});
test("27 archive nasconde e restore ripristina",async()=>{await archiveCrmOpportunity(sales(),ids.opportunity);assert.equal(await getCrmOpportunity(sales(),ids.opportunity) !== null,true);assert.equal((await getCrmOpportunities(sales())).length,0);await archiveCrmOpportunity(sales(),ids.opportunity,true);assert.equal((await getCrmOpportunities(sales())).length,1)});
