import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { createServer, type Server, type Socket } from "node:net";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { FusionCatalogSyncController, startFusionRuntime } from "../../tools/kitchen-connector/catalog-sync-runtime";
import { buildFusionDataRequest, catalogFingerprint, FusionCatalogError, FusionCatalogReader, FusionCatalogSnapshotStore, isFusionCatalogPlaceholder, parseFusionCatalogFrame, reconcileCatalog, type FusionCatalogDiagnosticCode } from "../../tools/kitchen-connector/fusion-catalog";
import { JsonSpool, KitchenConnectorClient, SimulatorPrinterAdapter } from "../../tools/kitchen-connector/runtime";

const close=(server:Server)=>new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));
async function simulator(frames:string[],options:{delay?:number;disconnect?:boolean}={}){const acknowledgements:string[]=[];let request="";const server=createServer(socket=>{socket.on("data",chunk=>{const value=chunk.toString();if(value.includes("<DATA_REQ>")){request+=value;send(socket,0);}else acknowledgements.push(value);});function send(target:Socket,index:number){if(options.disconnect)return target.destroy();if(index>=frames.length)return;setTimeout(()=>{target.write(frames[index]);send(target,index+1);},options.delay??5);}});await new Promise<void>(resolve=>server.listen(0,"127.0.0.1",resolve));const address=server.address();if(!address||typeof address==="string")throw new Error();return{server,port:address.port,acknowledgements,request:()=>request};}
const config=(port:number,readTimeoutMs=200)=>({host:"127.0.0.1",port,upperBoundPlu:10,connectTimeoutMs:100,readTimeoutMs,writeTimeoutMs:100,maxFrameBytes:4096,maxItems:10});

test("DATA_REQ builder and parser accept only proven catalog fields",()=>{assert.equal(buildFusionDataRequest(2),"<CE><DATA_REQ><PLU>2</PLU></DATA_REQ></CE>");const parsed=parseFusionCatalogFrame("<CE><DATA_SEND><PLU>2<DESC>  CONTORNO  </DESC><PRICE>400</PRICE></PLU></DATA_SEND></CE>");assert.equal(parsed.kind,"ITEM");if(parsed.kind==="ITEM"){assert.equal(parsed.item.name,"CONTORNO");assert.equal(parsed.item.priceCents,400);}assert.deepEqual(parseFusionCatalogFrame("<CE><DB_END/></CE>"),{kind:"END"});});
test("parser rejects invalid frames with bounded field-specific diagnostics",()=>{
  const cases:[FusionCatalogDiagnosticCode,string][]=[
    ["INVALID_PLU","<CE><DATA_SEND><PLU>x<DESC>X</DESC><PRICE>1</PRICE></PLU></DATA_SEND></CE>"],
    ["MISSING_DESC","<CE><DATA_SEND><PLU>1<PRICE>1</PRICE></PLU></DATA_SEND></CE>"],
    ["EMPTY_DESC","<CE><DATA_SEND><PLU>1<DESC>  </DESC><PRICE>1</PRICE></PLU></DATA_SEND></CE>"],
    ["INVALID_PRICE","<CE><DATA_SEND><PLU>1<DESC>X</DESC><PRICE>-1</PRICE></PLU></DATA_SEND></CE>"],
    ["INVALID_FRAME_STRUCTURE","<CE><ACK></ACK></CE>"],
    ["INVALID_FRAME_STRUCTURE",`<CE><DATA_SEND><PLU>1<DESC>${"x".repeat(600)}`],
  ];
  for(const [code,frame] of cases)assert.throws(()=>parseFusionCatalogFrame(frame),error=>{assert.ok(error instanceof FusionCatalogError);assert.equal(error.code,code);assert.equal(error.diagnostic?.code,code);assert.equal(error.diagnostic?.frameByteLength,Buffer.byteLength(frame));assert.ok(Buffer.from(error.diagnostic?.frameHex??"","hex").length<=512);assert.equal(error.diagnostic?.truncated,Buffer.byteLength(frame)>512);assert.doesNotMatch(error.message,/credential|secret/i);return true;});
});
test("reader handles one/many PLUs, gaps, duplicate records and ACKs DB_END",async()=>{const fake=await simulator(["<CE><DATA_SEND><PLU>1<DESC>UNO</DESC><PRICE>100</PRICE></PLU></DATA_SEND></CE>","<CE><DATA_SEND><PLU>3<DESC>TRE</DESC><PRICE>300</PRICE></PLU></DATA_SEND></CE>","<CE><DATA_SEND><PLU>3<DESC>TRE</DESC><PRICE>300</PRICE></PLU></DATA_SEND></CE>","<CE><DB_END/></CE>"]);try{const result=await new FusionCatalogReader(config(fake.port)).read();assert.deepEqual(result.map(item=>item.plu),[1,3]);assert.equal(fake.request(),buildFusionDataRequest(10));await new Promise(resolve=>setTimeout(resolve,20));assert.equal(fake.acknowledgements.join("").match(/<CE><ACK><\/ACK><\/CE>/g)?.length,4);}finally{await close(fake.server);}});
test("reader fails closed on malformed, timeout, disconnect and conflicting duplicate",async()=>{for(const frames of [["malformed</CE>"],["<CE><DATA_SEND><PLU>1<DESC>A</DESC><PRICE>1</PRICE></PLU></DATA_SEND></CE>","<CE><DATA_SEND><PLU>1<DESC>B</DESC><PRICE>1</PRICE></PLU></DATA_SEND></CE>"]]){const fake=await simulator(frames);try{await assert.rejects(new FusionCatalogReader(config(fake.port)).read());}finally{await close(fake.server);}}const timeout=await simulator([], {delay:500});try{await assert.rejects(new FusionCatalogReader(config(timeout.port,30)).read(),/TIMEOUT/);}finally{await close(timeout.server);}const disconnected=await simulator([],{disconnect:true});try{await assert.rejects(new FusionCatalogReader(config(disconnected.port)).read());}finally{await close(disconnected.server);}});
test("change detection covers new, price/name changes, unchanged and missing without deletion",()=>{const oldItem={plu:1,name:"OLD",priceCents:100,rawFingerprint:catalogFingerprint({plu:1,name:"OLD",priceCents:100}),lastSeenAt:"a",lastChangedAt:"a",syncState:"SYNCED" as const};const previous={version:1 as const,completedAt:"a",items:{"1":oldItem,"2":{...oldItem,plu:2,rawFingerprint:catalogFingerprint({plu:2,name:"OLD",priceCents:100})}}};const current=[{plu:1,name:"NEW",priceCents:200,rawFingerprint:catalogFingerprint({plu:1,name:"NEW",priceCents:200})},{plu:3,name:"THREE",priceCents:null,rawFingerprint:catalogFingerprint({plu:3,name:"THREE",priceCents:null})}];const result=reconcileCatalog(previous,current,"b");assert.deepEqual(result.changed.map(item=>item.plu),[1,3]);assert.deepEqual(result.missing,[2]);assert.equal(result.snapshot.items["2"].syncState,"MISSING_FROM_FUSION");assert.equal(Object.keys(result.snapshot.items).length,3);});
test("exact PLU placeholders are skipped but real PLU names and later product names import",()=>{const placeholder={plu:24,name:"PLU24",priceCents:1000,rawFingerprint:catalogFingerprint({plu:24,name:"PLU24",priceCents:1000})};assert.equal(isFusionCatalogPlaceholder(placeholder),true);assert.equal(isFusionCatalogPlaceholder({...placeholder,name:"PLU SPECIAL"}),false);const first=reconcileCatalog({version:1,completedAt:"a",items:{}},[placeholder,{...placeholder,plu:25,name:"PLU SPECIAL",rawFingerprint:catalogFingerprint({plu:25,name:"PLU SPECIAL",priceCents:1000})}],"b");assert.equal(first.placeholdersSkipped,1);assert.deepEqual(first.changed.map(item=>item.plu),[25]);assert.equal(first.snapshot.items["24"].syncState,"PLACEHOLDER_SKIPPED");const real={...placeholder,name:"ORECCHIETTE",rawFingerprint:catalogFingerprint({plu:24,name:"ORECCHIETTE",priceCents:1000})};const second=reconcileCatalog(first.snapshot,[real],"c");assert.equal(second.placeholdersSkipped,0);assert.deepEqual(second.changed.map(item=>item.plu),[24]);});
test("heartbeat remains independent while a catalog sync is still running",async()=>{let heartbeats=0;let release!:()=>void;const blocked=new Promise<void>(resolve=>{release=resolve;});const stop=startFusionRuntime({pollOnce:async()=>undefined,heartbeat:async()=>{heartbeats++;return{};}},{request:()=>undefined,tick:async()=>{await blocked;return true;}},{pollMs:5,heartbeatMs:5,catalogMs:1_000,onError:()=>undefined});try{await new Promise(resolve=>setTimeout(resolve,35));assert.ok(heartbeats>=3);}finally{release();stop();}});
test("catalog watchdog persists ERROR and single-flight rejects a concurrent tick",async()=>{const directory=await mkdtemp(join(tmpdir(),"fusion-catalog-watchdog-")),fusion=await simulator([]),uploads:Record<string,unknown>[]=[];const http=(await import("node:http")).createServer(async(request,response)=>{let body="";for await(const chunk of request)body+=chunk;uploads.push(JSON.parse(body));response.setHeader("content-type","application/json");response.end(JSON.stringify({ok:true}));});await new Promise<void>(resolve=>http.listen(0,"127.0.0.1",resolve));const address=http.address();if(!address||typeof address==="string")throw new Error();try{const client=new KitchenConnectorClient(`http://127.0.0.1:${address.port}`,"device",new JsonSpool(join(directory,"spool")),new SimulatorPrinterAdapter()),controller=new FusionCatalogSyncController({enabled:true,intervalMs:10_000,fullIntervalMs:60_000,maxBackoffMs:30_000,watchdogMs:30},new FusionCatalogReader({...config(fusion.port,1_000)}),new FusionCatalogSnapshotStore(join(directory,"snapshot.json")),client);const first=controller.tick(true);assert.equal(await controller.tick(true),false);await assert.rejects(first,/CATALOG_SYNC_WATCHDOG_TIMEOUT/);assert.equal(uploads[0].status,"SYNCING");assert.equal(uploads.at(-1)?.status,"ERROR");assert.equal(uploads.at(-1)?.runId,uploads[0].runId);}finally{await close(fusion.server);await new Promise<void>(resolve=>http.close(()=>resolve()));await rm(directory,{recursive:true});}});
test("API network failure releases single-flight for a later retry",async()=>{const directory=await mkdtemp(join(tmpdir(),"fusion-catalog-network-")),closed=(await import("node:http")).createServer();await new Promise<void>(resolve=>closed.listen(0,"127.0.0.1",resolve));const address=closed.address();if(!address||typeof address==="string")throw new Error();await new Promise<void>(resolve=>closed.close(()=>resolve()));try{const client=new KitchenConnectorClient(`http://127.0.0.1:${address.port}`,"device",new JsonSpool(join(directory,"spool")),new SimulatorPrinterAdapter()),controller=new FusionCatalogSyncController({enabled:true,intervalMs:10_000,fullIntervalMs:60_000,maxBackoffMs:30_000,watchdogMs:100},new FusionCatalogReader(config(address.port)),new FusionCatalogSnapshotStore(join(directory,"snapshot.json")),client);await assert.rejects(controller.tick(true));await assert.rejects(controller.tick(true));}finally{await rm(directory,{recursive:true});}});
test("snapshot survives restart and quarantines no valid state on interrupted temp write",async()=>{const directory=await mkdtemp(join(tmpdir(),"fusion-catalog-")),path=join(directory,"catalog.json"),store=new FusionCatalogSnapshotStore(path);try{const snapshot=reconcileCatalog(await store.load(),[{plu:1,name:"ONE",priceCents:100,rawFingerprint:catalogFingerprint({plu:1,name:"ONE",priceCents:100})}],"now").snapshot;await store.save(snapshot);assert.deepEqual(await new FusionCatalogSnapshotStore(path).load(),snapshot);}finally{await rm(directory,{recursive:true});}});
