import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { after, before, test } from "node:test";
import { acknowledgeConnectorJob, claimConnectorJob, createPairingToken, failConnectorJob, fetchConnectorJobs, pairConnector } from "../../lib/kitchen-connector";
import { prisma } from "../../lib/prisma";

const databaseName=new URL(process.env.DATABASE_URL??"postgresql://invalid/invalid").pathname.slice(1);
if(!databaseName.endsWith("_test"))throw new Error("FUSION DB tests require a database ending in _test.");
let fixture:Awaited<ReturnType<typeof createFixture>>;

async function createFixture(){const suffix=randomUUID().slice(0,8),company=await prisma.company.create({data:{name:`Fusion ${suffix}`,vatNumber:`FX${suffix}`}}),user=await prisma.user.create({data:{email:`fusion-${suffix}@test.invalid`,firstName:"Fusion",lastName:"Test",password:"test"}}),location=await prisma.location.create({data:{companyId:company.id,code:"FX",slug:`fusion-${suffix}`,name:"Fusion test"}}),station=await prisma.kitchenStation.create({data:{companyId:company.id,locationId:location.id,code:"FUSION",name:"Fusion"}}),printer=await prisma.restaurantPrinter.create({data:{companyId:company.id,locationId:location.id,stationId:station.id,code:"F1745",name:"Fusion XML1745",type:"FUSION_XML_1745",connectionType:"TCP"}});const pairing=await createPairingToken(company.id,location.id,printer.id,user.id),paired=await pairConnector(pairing.pairingToken,{name:"fusion-test"});return{company,user,location,station,printer,device:{id:paired.deviceId,companyId:company.id,locationId:location.id,printerId:printer.id,leaseSeconds:60}};}
async function job(key:string){return prisma.kitchenPrintJob.create({data:{companyId:fixture.company.id,locationId:fixture.location.id,stationId:fixture.station.id,printerId:fixture.printer.id,printType:"KITCHEN_TICKET",payload:"structured-by-claim",idempotencyKey:key,requestedById:fixture.user.id}});}

before(async()=>{fixture=await createFixture();});
after(async()=>{const companyId=fixture.company.id;await prisma.auditLog.deleteMany({where:{companyId}});await prisma.kitchenPrintJob.deleteMany({where:{companyId}});await prisma.kitchenConnectorDevice.deleteMany({where:{companyId}});await prisma.kitchenConnectorPairingToken.deleteMany({where:{companyId}});await prisma.restaurantPrinter.deleteMany({where:{companyId}});await prisma.kitchenStation.deleteMany({where:{companyId}});await prisma.location.deleteMany({where:{companyId}});await prisma.company.delete({where:{id:companyId}});await prisma.user.delete({where:{id:fixture.user.id}});await prisma.$disconnect();});

test("FUSION enum config, lease concurrency, ACK and duplicate suppression persist",async()=>{assert.equal(fixture.printer.type,"FUSION_XML_1745");assert.equal(fixture.printer.connectionType,"TCP");const created=await job("fusion:ack");const claims=await Promise.allSettled([claimConnectorJob(fixture.device,created.id),claimConnectorJob(fixture.device,created.id)]);assert.equal(claims.filter(result=>result.status==="fulfilled").length,1);const claim=(claims.find(result=>result.status==="fulfilled") as PromiseFulfilledResult<Awaited<ReturnType<typeof claimConnectorJob>>>).value;assert.equal((await acknowledgeConnectorJob(fixture.device,created.id,claim.leaseToken)).status,"PRINTED");await assert.rejects(claimConnectorJob(fixture.device,created.id));assert.equal((await fetchConnectorJobs(fixture.device)).some(row=>row.id===created.id),false);});

test("NACK and UNCERTAIN persist as terminal failures and scheduler does not reclaim",async()=>{for(const [key,error] of [["fusion:nack1","FUSION_NACK_1"],["fusion:nack2","FUSION_NACK_2"],["fusion:uncertain","FUSION_UNCERTAIN_DELIVERY"]] as const){const created=await job(key),claim=await claimConnectorJob(fixture.device,created.id),failed=await failConnectorJob(fixture.device,created.id,claim.leaseToken,error);assert.equal(failed.status,"FAILED");assert.match(failed.lastError??"",new RegExp(error));assert.equal((await fetchConnectorJobs(fixture.device)).some(row=>row.id===created.id),false);await assert.rejects(claimConnectorJob(fixture.device,created.id));}});
