import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { mkdtemp,rm } from "node:fs/promises";
import { createServer as createHttpServer } from "node:http";
import { createServer as createTcpServer } from "node:net";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { after, before, test } from "node:test";
import { POST as catalogEndpoint } from "../../app/api/kitchen-connector/v1/catalog-sync/route";
import { getFusionCatalogCommand, requestFusionCatalogSync, syncFusionCatalog } from "../../lib/fusion-catalog-sync";
import { createPairingToken, pairConnector } from "../../lib/kitchen-connector";
import { prisma } from "../../lib/prisma";
import { catalogFingerprint } from "../../tools/kitchen-connector/fusion-catalog";
import { FusionCatalogReader,FusionCatalogSnapshotStore } from "../../tools/kitchen-connector/fusion-catalog";
import { FusionCatalogSyncController } from "../../tools/kitchen-connector/catalog-sync-runtime";
import { JsonSpool,KitchenConnectorClient,SimulatorPrinterAdapter } from "../../tools/kitchen-connector/runtime";

const databaseName=new URL(process.env.DATABASE_URL??"postgresql://invalid/invalid").pathname.slice(1);
if(!databaseName.endsWith("_test"))throw new Error("Fusion Catalog DB tests require a database ending in _test.");
let fixture:Awaited<ReturnType<typeof createFixture>>;
const inputItem=(plu:number,name:string,priceCents:number|null)=>({plu,name,priceCents,fingerprint:catalogFingerprint({plu,name,priceCents})});

async function createFixture(){const suffix=randomUUID().slice(0,8),company=await prisma.company.create({data:{name:`Catalog ${suffix}`,vatNumber:`FC${suffix}`}}),otherCompany=await prisma.company.create({data:{name:`Other ${suffix}`,vatNumber:`FO${suffix}`}}),user=await prisma.user.create({data:{email:`catalog-${suffix}@test.invalid`,firstName:"Catalog",lastName:"Test",password:"test"}}),location=await prisma.location.create({data:{companyId:company.id,code:"FC",slug:`catalog-${suffix}`,name:"Catalog"}}),otherLocation=await prisma.location.create({data:{companyId:company.id,code:"FC2",slug:`catalog-other-${suffix}`,name:"Other"}}),station=await prisma.kitchenStation.create({data:{companyId:company.id,locationId:location.id,code:"F",name:"Fusion"}}),printer=await prisma.restaurantPrinter.create({data:{companyId:company.id,locationId:location.id,stationId:station.id,code:"FUSION",name:"Fusion",type:"FUSION_XML_1745",connectionType:"TCP"}});await prisma.unitOfMeasure.create({data:{companyId:company.id,code:"PZ",name:"Pezzo",symbol:"pz",precision:0}});const pairing=await createPairingToken(company.id,location.id,printer.id,user.id),paired=await pairConnector(pairing.pairingToken,{name:"catalog-db"});return{company,otherCompany,user,location,otherLocation,station,printer,credential:paired.credential,device:{id:paired.deviceId,companyId:company.id,locationId:location.id}};}
before(async()=>{fixture=await createFixture();});
after(async()=>{const companyId=fixture.company.id;await prisma.auditLog.deleteMany({where:{companyId}});await prisma.idempotencyRecord.deleteMany({where:{companyId}});await prisma.fusionCatalogSyncState.deleteMany({where:{companyId}});await prisma.fusionCatalogMapping.deleteMany({where:{companyId}});await prisma.kitchenPrintJob.deleteMany({where:{companyId}});await prisma.kitchenConnectorDevice.deleteMany({where:{companyId}});await prisma.kitchenConnectorPairingToken.deleteMany({where:{companyId}});await prisma.restaurantPrinter.deleteMany({where:{companyId}});await prisma.kitchenStation.deleteMany({where:{companyId}});await prisma.item.deleteMany({where:{companyId}});await prisma.unitOfMeasure.deleteMany({where:{companyId}});await prisma.location.deleteMany({where:{companyId}});await prisma.company.deleteMany({where:{id:{in:[companyId,fixture.otherCompany.id]}}});await prisma.user.delete({where:{id:fixture.user.id}});await prisma.$disconnect();});

test("authenticated endpoint imports, updates, preserves Nexus fields and is idempotent",async()=>{const before={documents:await prisma.businessDocument.count({where:{companyId:fixture.company.id}}),financial:await prisma.financialMovement.count({where:{companyId:fixture.company.id}}),orders:await prisma.restaurantOrder.count({where:{companyId:fixture.company.id}}),jobs:await prisma.kitchenPrintJob.count({where:{companyId:fixture.company.id}})};const post=(body:unknown,credential=fixture.credential)=>catalogEndpoint(new Request("http://test/api/kitchen-connector/v1/catalog-sync",{method:"POST",headers:{authorization:`Bearer ${credential}`},body:JSON.stringify(body)}));
  const firstBody={idempotencyKey:"catalog:first-sync",requestVersion:0,totalCount:1,unchangedCount:0,items:[inputItem(2,"CONTORNO",400)],missingPlus:[],companyId:fixture.otherCompany.id,locationId:fixture.otherLocation.id};const first=await post(firstBody);assert.equal(first.status,200);assert.deepEqual(await first.json(),{ok:true,created:1,updated:0,unchanged:0,missing:0,placeholdersSkipped:0});const retry=await post(firstBody);assert.equal(retry.status,200);assert.equal(await prisma.item.count({where:{companyId:fixture.company.id,code:"FUSION_2"}}),1);assert.equal(await prisma.fusionCatalogMapping.count({where:{companyId:fixture.company.id,locationId:fixture.location.id,plu:2}}),1);assert.equal(await prisma.fusionCatalogMapping.count({where:{locationId:fixture.otherLocation.id}}),0);
  const mapping=await prisma.fusionCatalogMapping.findUniqueOrThrow({where:{companyId_locationId_plu:{companyId:fixture.company.id,locationId:fixture.location.id,plu:2}}});await prisma.item.update({where:{id:mapping.itemId},data:{description:"Nexus marketing",imageUrl:"https://example.invalid/image.jpg",internalNotes:"Nexus analytics"}});const update=await post({idempotencyKey:"catalog:update-sync",requestVersion:0,totalCount:1,unchangedCount:0,items:[inputItem(2,"CONTORNO GRANDE",450)],missingPlus:[]});assert.equal(update.status,200);const item=await prisma.item.findUniqueOrThrow({where:{id:mapping.itemId}});assert.equal(item.name,"CONTORNO GRANDE");assert.equal(item.salePrice?.toFixed(2),"4.50");assert.equal(item.description,"Nexus marketing");assert.equal(item.imageUrl,"https://example.invalid/image.jpg");assert.equal(item.internalNotes,"Nexus analytics");
  const unchanged=await post({idempotencyKey:"catalog:unchanged-sync",requestVersion:0,totalCount:1,unchangedCount:1,items:[],missingPlus:[]});assert.deepEqual(await unchanged.json(),{ok:true,created:0,updated:0,unchanged:1,missing:0,placeholdersSkipped:0});const missing=await post({idempotencyKey:"catalog:missing-sync",requestVersion:0,totalCount:0,unchangedCount:0,items:[],missingPlus:[2]});assert.equal(missing.status,200);assert.equal((await prisma.fusionCatalogMapping.findUniqueOrThrow({where:{id:mapping.id}})).missingFromFusion,true);assert.ok(await prisma.item.findUnique({where:{id:mapping.itemId}}));assert.ok(await prisma.auditLog.findFirst({where:{companyId:fixture.company.id,action:"FUSION_CATALOG_SYNCED"}}));
  assert.equal((await post(firstBody,"device_invalid")).status,401);const after={documents:await prisma.businessDocument.count({where:{companyId:fixture.company.id}}),financial:await prisma.financialMovement.count({where:{companyId:fixture.company.id}}),orders:await prisma.restaurantOrder.count({where:{companyId:fixture.company.id}}),jobs:await prisma.kitchenPrintJob.count({where:{companyId:fixture.company.id}})};assert.deepEqual(after,before);
});

test("server skips an exact placeholder and imports it after it gets a real name",async()=>{const placeholder=await syncFusionCatalog(fixture.device,{idempotencyKey:"catalog:placeholder-24",requestVersion:0,totalCount:1,unchangedCount:0,items:[inputItem(24,"PLU24",1000)],missingPlus:[]});assert.deepEqual(placeholder,{created:0,updated:0,unchanged:0,missing:0,placeholdersSkipped:1});assert.equal(await prisma.item.count({where:{companyId:fixture.company.id,code:"FUSION_24"}}),0);assert.equal(await prisma.fusionCatalogMapping.count({where:{companyId:fixture.company.id,locationId:fixture.location.id,plu:24}}),0);const special=await syncFusionCatalog(fixture.device,{idempotencyKey:"catalog:plu-special",requestVersion:0,totalCount:1,unchangedCount:0,items:[inputItem(25,"PLU SPECIAL",1000)],missingPlus:[]});assert.equal(special.created,1);const real=await syncFusionCatalog(fixture.device,{idempotencyKey:"catalog:real-24",requestVersion:0,totalCount:1,unchangedCount:0,items:[inputItem(24,"ORECCHIETTE",1200)],missingPlus:[]});assert.equal(real.created,1);assert.equal((await prisma.item.findFirstOrThrow({where:{companyId:fixture.company.id,code:"FUSION_24"}})).name,"ORECCHIETTE");});

test("status endpoint finalizes a failed sync as ERROR with its diagnostic",async()=>{const post=(body:unknown)=>catalogEndpoint(new Request("http://test/api/kitchen-connector/v1/catalog-sync",{method:"POST",headers:{authorization:`Bearer ${fixture.credential}`},body:JSON.stringify(body)}));assert.equal((await post({status:"SYNCING"})).status,200);assert.equal((await prisma.fusionCatalogSyncState.findUniqueOrThrow({where:{connectorId:fixture.device.id}})).status,"SYNCING");assert.equal((await post({status:"ERROR",error:"CATALOG_SYNC_WATCHDOG_TIMEOUT"})).status,200);const state=await prisma.fusionCatalogSyncState.findUniqueOrThrow({where:{connectorId:fixture.device.id}});assert.equal(state.status,"ERROR");assert.equal(state.lastError,"CATALOG_SYNC_WATCHDOG_TIMEOUT");});

test("duplicate PLU and later collision fail atomically",async()=>{await assert.rejects(syncFusionCatalog(fixture.device,{idempotencyKey:"catalog:duplicate",requestVersion:0,totalCount:2,unchangedCount:0,items:[inputItem(7,"A",100),inputItem(7,"B",200)],missingPlus:[]}));await prisma.item.create({data:{companyId:fixture.company.id,code:"FUSION_99",type:"PRODUCT",name:"Collision"}});await assert.rejects(syncFusionCatalog(fixture.device,{idempotencyKey:"catalog:rollback",requestVersion:0,totalCount:2,unchangedCount:0,items:[inputItem(98,"FIRST",100),inputItem(99,"COLLISION",100)],missingPlus:[]}));assert.equal(await prisma.item.count({where:{companyId:fixture.company.id,code:"FUSION_98"}}),0);assert.equal(await prisma.fusionCatalogMapping.count({where:{companyId:fixture.company.id,plu:98}}),0);});

test("manual sync command is scoped and rapid requests are versioned",async()=>{const states=await Promise.all([requestFusionCatalogSync(fixture.company.id,fixture.location.id,fixture.user.id),requestFusionCatalogSync(fixture.company.id,fixture.location.id,fixture.user.id)]);assert.notEqual(states[0].manualRequestVersion,states[1].manualRequestVersion);const command=await getFusionCatalogCommand(fixture.device);assert.equal(command.catalogSyncRequested,true);assert.equal(command.requestVersion,Math.max(...states.map(state=>state.manualRequestVersion)));assert.deepEqual(await getFusionCatalogCommand({id:fixture.device.id,companyId:fixture.otherCompany.id,locationId:fixture.location.id}),{catalogSyncRequested:false,requestVersion:0});});

test("manual command drives simulated DATA_REQ through connector upload into Nexus",async()=>{const directory=await mkdtemp(join(tmpdir(),"fusion-catalog-db-")),tcp=createTcpServer(socket=>{let stage=0;socket.on("data",chunk=>{const text=chunk.toString();if(stage===0&&text.includes("<DATA_REQ>")){stage=1;socket.write("<CE><DATA_SEND><PLU>11<DESC>SIMULATED</DESC><PRICE>725</PRICE></PLU></DATA_SEND></CE>");}else if(stage===1&&text.includes("<ACK>")){stage=2;socket.write("<CE><DB_END/></CE>");}else if(stage===2&&text.includes("<ACK>")){stage=3;socket.end();}});});await new Promise<void>(resolve=>tcp.listen(0,"127.0.0.1",resolve));const tcpAddress=tcp.address();if(!tcpAddress||typeof tcpAddress==="string")throw new Error("TCP simulator unavailable");const http=createHttpServer(async(request,response)=>{const chunks:Buffer[]=[];for await(const chunk of request)chunks.push(Buffer.from(chunk));const result=await catalogEndpoint(new Request(`http://test${request.url}`,{method:request.method,headers:{authorization:String(request.headers.authorization??"")},body:Buffer.concat(chunks).toString()}));response.statusCode=result.status;response.setHeader("content-type","application/json");response.end(await result.text());});await new Promise<void>(resolve=>http.listen(0,"127.0.0.1",resolve));const httpAddress=http.address();if(!httpAddress||typeof httpAddress==="string")throw new Error("HTTP simulator unavailable");try{const command=await getFusionCatalogCommand(fixture.device),client=new KitchenConnectorClient(`http://127.0.0.1:${httpAddress.port}`,fixture.credential,new JsonSpool(join(directory,"spool")),new SimulatorPrinterAdapter()),controller=new FusionCatalogSyncController({enabled:true,intervalMs:10_000,fullIntervalMs:900_000,maxBackoffMs:300_000},new FusionCatalogReader({host:"127.0.0.1",port:tcpAddress.port,upperBoundPlu:20,connectTimeoutMs:200,readTimeoutMs:200,writeTimeoutMs:200,maxFrameBytes:4096,maxItems:20}),new FusionCatalogSnapshotStore(join(directory,"catalog.json")),client);controller.request(command.requestVersion);assert.equal(await controller.tick(true),true);const mapping=await prisma.fusionCatalogMapping.findUniqueOrThrow({where:{companyId_locationId_plu:{companyId:fixture.company.id,locationId:fixture.location.id,plu:11}}}),item=await prisma.item.findUniqueOrThrow({where:{id:mapping.itemId}});assert.equal(item.name,"SIMULATED");assert.equal(item.salePrice?.toFixed(2),"7.25");assert.equal((await getFusionCatalogCommand(fixture.device)).catalogSyncRequested,false);}finally{await new Promise<void>(resolve=>http.close(()=>resolve()));await new Promise<void>(resolve=>tcp.close(()=>resolve()));await rm(directory,{recursive:true});}});
