import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { createServer, type Server, type Socket } from "node:net";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { buildFusionDataRequest, catalogFingerprint, FusionCatalogReader, FusionCatalogSnapshotStore, parseFusionCatalogFrame, reconcileCatalog } from "../../tools/kitchen-connector/fusion-catalog";

const close=(server:Server)=>new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));
async function simulator(frames:string[],options:{delay?:number;disconnect?:boolean}={}){const acknowledgements:string[]=[];let request="";const server=createServer(socket=>{socket.on("data",chunk=>{const value=chunk.toString();if(value.includes("<DATA_REQ>")){request+=value;send(socket,0);}else acknowledgements.push(value);});function send(target:Socket,index:number){if(options.disconnect)return target.destroy();if(index>=frames.length)return;setTimeout(()=>{target.write(frames[index]);send(target,index+1);},options.delay??5);}});await new Promise<void>(resolve=>server.listen(0,"127.0.0.1",resolve));const address=server.address();if(!address||typeof address==="string")throw new Error();return{server,port:address.port,acknowledgements,request:()=>request};}
const config=(port:number,readTimeoutMs=200)=>({host:"127.0.0.1",port,upperBoundPlu:10,connectTimeoutMs:100,readTimeoutMs,writeTimeoutMs:100,maxFrameBytes:4096,maxItems:10});

test("DATA_REQ builder and parser accept only proven catalog fields",()=>{assert.equal(buildFusionDataRequest(2),"<CE><DATA_REQ><PLU>2</PLU></DATA_REQ></CE>");const parsed=parseFusionCatalogFrame("<CE><DATA_SEND><PLU>2<DESC>  CONTORNO  </DESC><PRICE>400</PRICE></PLU></DATA_SEND></CE>");assert.equal(parsed.kind,"ITEM");if(parsed.kind==="ITEM"){assert.equal(parsed.item.name,"CONTORNO");assert.equal(parsed.item.priceCents,400);}assert.deepEqual(parseFusionCatalogFrame("<CE><DB_END/></CE>"),{kind:"END"});for(const malformed of ["<CE><ACK></ACK></CE>","<CE><DATA_SEND><PLU>x<DESC>X</DESC></PLU></DATA_SEND></CE>","<CE><DATA_SEND><PLU>1<PRICE>1</PRICE></PLU></DATA_SEND></CE>"])assert.throws(()=>parseFusionCatalogFrame(malformed));});
test("reader handles one/many PLUs, gaps, duplicate records and ACKs DB_END",async()=>{const fake=await simulator(["<CE><DATA_SEND><PLU>1<DESC>UNO</DESC><PRICE>100</PRICE></PLU></DATA_SEND></CE>","<CE><DATA_SEND><PLU>3<DESC>TRE</DESC><PRICE>300</PRICE></PLU></DATA_SEND></CE>","<CE><DATA_SEND><PLU>3<DESC>TRE</DESC><PRICE>300</PRICE></PLU></DATA_SEND></CE>","<CE><DB_END/></CE>"]);try{const result=await new FusionCatalogReader(config(fake.port)).read();assert.deepEqual(result.map(item=>item.plu),[1,3]);assert.equal(fake.request(),buildFusionDataRequest(10));await new Promise(resolve=>setTimeout(resolve,20));assert.equal(fake.acknowledgements.join("").match(/<CE><ACK><\/ACK><\/CE>/g)?.length,4);}finally{await close(fake.server);}});
test("reader fails closed on malformed, timeout, disconnect and conflicting duplicate",async()=>{for(const frames of [["malformed</CE>"],["<CE><DATA_SEND><PLU>1<DESC>A</DESC><PRICE>1</PRICE></PLU></DATA_SEND></CE>","<CE><DATA_SEND><PLU>1<DESC>B</DESC><PRICE>1</PRICE></PLU></DATA_SEND></CE>"]]){const fake=await simulator(frames);try{await assert.rejects(new FusionCatalogReader(config(fake.port)).read());}finally{await close(fake.server);}}const timeout=await simulator([], {delay:500});try{await assert.rejects(new FusionCatalogReader(config(timeout.port,30)).read(),/TIMEOUT/);}finally{await close(timeout.server);}const disconnected=await simulator([],{disconnect:true});try{await assert.rejects(new FusionCatalogReader(config(disconnected.port)).read());}finally{await close(disconnected.server);}});
test("change detection covers new, price/name changes, unchanged and missing without deletion",()=>{const oldItem={plu:1,name:"OLD",priceCents:100,rawFingerprint:catalogFingerprint({plu:1,name:"OLD",priceCents:100}),lastSeenAt:"a",lastChangedAt:"a",syncState:"SYNCED" as const};const previous={version:1 as const,completedAt:"a",items:{"1":oldItem,"2":{...oldItem,plu:2,rawFingerprint:catalogFingerprint({plu:2,name:"OLD",priceCents:100})}}};const current=[{plu:1,name:"NEW",priceCents:200,rawFingerprint:catalogFingerprint({plu:1,name:"NEW",priceCents:200})},{plu:3,name:"THREE",priceCents:null,rawFingerprint:catalogFingerprint({plu:3,name:"THREE",priceCents:null})}];const result=reconcileCatalog(previous,current,"b");assert.deepEqual(result.changed.map(item=>item.plu),[1,3]);assert.deepEqual(result.missing,[2]);assert.equal(result.snapshot.items["2"].syncState,"MISSING_FROM_FUSION");assert.equal(Object.keys(result.snapshot.items).length,3);});
test("snapshot survives restart and quarantines no valid state on interrupted temp write",async()=>{const directory=await mkdtemp(join(tmpdir(),"fusion-catalog-")),path=join(directory,"catalog.json"),store=new FusionCatalogSnapshotStore(path);try{const snapshot=reconcileCatalog(await store.load(),[{plu:1,name:"ONE",priceCents:100,rawFingerprint:catalogFingerprint({plu:1,name:"ONE",priceCents:100})}],"now").snapshot;await store.save(snapshot);assert.deepEqual(await new FusionCatalogSnapshotStore(path).load(),snapshot);}finally{await rm(directory,{recursive:true});}});
