import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { after, before, test } from "node:test";
import { getCompanySettings, updateCompanySettings } from "../../lib/company-settings";
import { hasMasterDataCapability } from "../../lib/master-data-access";
import { createCategory, createUnit, createVatRate, getMasterData, MasterDataError, updateCategory, updateUnit, updateVatRate } from "../../lib/master-data";
import { createLocation, LocationDomainError, updateLocation } from "../../lib/locations";
import { prisma } from "../../lib/prisma";

const databaseUrl = process.env.DATABASE_URL ?? "";
if (!new URL(databaseUrl).pathname.replace(/^\//, "").endsWith("_test")) throw new Error("I test master data richiedono un database con suffisso _test.");
let companyId = "", otherCompanyId = "", userId = "", locationId = "";
const ids = { vat: [] as string[], unit: [] as string[], category: [] as string[] };

before(async () => { const company = await prisma.company.findUniqueOrThrow({ where: { vatNumber: "IT00000000000" } }); const member = await prisma.membership.findFirstOrThrow({ where: { companyId: company.id, active: true } }); const other = await prisma.company.create({ data: { name: `Master tenant ${randomUUID()}` } }); companyId = company.id; otherCompanyId = other.id; userId = member.userId; });
after(async () => { if (locationId) await prisma.location.deleteMany({ where: { id: locationId } }); await prisma.itemCategory.deleteMany({ where: { id: { in: ids.category } } }); await prisma.vatRate.deleteMany({ where: { id: { in: ids.vat } } }); await prisma.unitOfMeasure.deleteMany({ where: { id: { in: ids.unit } } }); if (otherCompanyId) await prisma.company.delete({ where: { id: otherCompanyId } }); await prisma.$disconnect(); });

test("Company: aggiornamento limitato alla società corrente", async () => { const before = await getCompanySettings(companyId); const otherBefore = await getCompanySettings(otherCompanyId); assert.ok(before); await updateCompanySettings(companyId, { name: before.name, legalName: before.legalName, vatNumber: before.vatNumber, taxCode: before.taxCode, country: before.country, address: before.address, city: before.city, email: before.email, phone: before.phone, currency: before.currency, timezone: before.timezone, locale: before.locale, logo: before.logo }); assert.deepEqual(await getCompanySettings(otherCompanyId), otherBefore); });
test("Location: update same tenant e cross-company negato", async () => { const code = `P01-${randomUUID().slice(0, 8)}`; const row = await createLocation(companyId, userId, { code, name: "P0.1 Location" }); locationId = row.id; await updateLocation(companyId, userId, row.id, { slug: row.slug, code, name: "P0.1 aggiornata" }); assert.equal((await prisma.location.findUniqueOrThrow({ where: { id: row.id } })).name, "P0.1 aggiornata"); await assert.rejects(updateLocation(otherCompanyId, userId, row.id, { slug: row.slug, code, name: "Cross" }), LocationDomainError); });
test("IVA: create/update, validazione percentuale e tenant isolation", async () => { const code = `V${randomUUID().slice(0, 7)}`; const row = await createVatRate(companyId, userId, { code, name: "IVA test", percentage: 22, active: true }); ids.vat.push(row.id); await updateVatRate(companyId, userId, row.id, { code, name: "IVA aggiornata", percentage: 10, active: true }); assert.equal(Number((await prisma.vatRate.findUniqueOrThrow({ where: { id: row.id } })).percentage), 10); assert.throws(() => createVatRate(companyId, userId, { code: "BAD", name: "Bad", percentage: 101 }), MasterDataError); await assert.rejects(updateVatRate(otherCompanyId, userId, row.id, { code, name: "Cross", percentage: 10 }), MasterDataError); assert.equal((await getMasterData(otherCompanyId)).vatRates.some((x) => x.id === row.id), false); });
test("UOM: create/update e codice duplicato", async () => { const code = `U${randomUUID().slice(0, 7)}`; const row = await createUnit(companyId, userId, { code, name: "Unità test", symbol: "pz", precision: 2 }); ids.unit.push(row.id); await updateUnit(companyId, userId, row.id, { code, name: "Unità aggiornata", symbol: "u", precision: 3 }); assert.equal((await prisma.unitOfMeasure.findUniqueOrThrow({ where: { id: row.id } })).precision, 3); await assert.rejects(createUnit(companyId, userId, { code, name: "Duplicata", symbol: "x", precision: 0 }), MasterDataError); });
test("Categorie: create/update tenant-safe", async () => { const code = `C${randomUUID().slice(0, 7)}`; const row = await createCategory(companyId, userId, { code, name: "Categoria test" }); ids.category.push(row.id); await updateCategory(companyId, userId, row.id, { code, name: "Categoria aggiornata", active: false }); assert.equal((await prisma.itemCategory.findUniqueOrThrow({ where: { id: row.id } })).active, false); await assert.rejects(updateCategory(otherCompanyId, userId, row.id, { code, name: "Cross" }), MasterDataError); });
test("RBAC master data", () => { assert.equal(hasMasterDataCapability(["SUPER_ADMIN"], "write"), true); assert.equal(hasMasterDataCapability(["ADMIN"], "write"), true); assert.equal(hasMasterDataCapability(["MANAGER"], "read"), true); assert.equal(hasMasterDataCapability(["MANAGER"], "write"), false); assert.equal(hasMasterDataCapability(["SALES"], "read"), false); });
