import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { after, before, test } from "node:test";
import { getCompanySettings, updateCompanySettings } from "../../lib/company-settings";
import { hasMasterDataCapability } from "../../lib/master-data-access";
import { canManageLocations, canReadLocations } from "../../lib/location-access";
import { createCategory, createUnit, createVatRate, getMasterData, MasterDataError, setCategoryActive, setUnitActive, setVatRateActive, updateCategory, updateUnit, updateVatRate } from "../../lib/master-data";
import { createLocation, LocationDomainError, updateLocation } from "../../lib/locations";
import { prisma } from "../../lib/prisma";

const databaseUrl = process.env.DATABASE_URL ?? "";
if (!new URL(databaseUrl).pathname.replace(/^\//, "").endsWith("_test")) throw new Error("I test master data richiedono un database con suffisso _test.");
let companyId = "", otherCompanyId = "", userId = "", locationId = "";
const ids = { vat: [] as string[], unit: [] as string[], category: [] as string[] };
const code = (prefix: string) => `${prefix}${randomUUID().slice(0, 7)}`.toUpperCase();

before(async () => { const company = await prisma.company.findUniqueOrThrow({ where: { vatNumber: "IT00000000000" } }); const member = await prisma.membership.findFirstOrThrow({ where: { companyId: company.id, active: true } }); const other = await prisma.company.create({ data: { name: `Master tenant ${randomUUID()}` } }); companyId = company.id; otherCompanyId = other.id; userId = member.userId; });
after(async () => { if (locationId) await prisma.auditLog.deleteMany({ where: { companyId, locationId } }); if (locationId) await prisma.location.deleteMany({ where: { id: locationId } }); await prisma.itemCategory.deleteMany({ where: { id: { in: ids.category } } }); await prisma.vatRate.deleteMany({ where: { id: { in: ids.vat } } }); await prisma.unitOfMeasure.deleteMany({ where: { id: { in: ids.unit } } }); if (otherCompanyId) await prisma.company.delete({ where: { id: otherCompanyId } }); await prisma.$disconnect(); });

test("Company update modifica il record esistente senza crearne altri", async () => { const before = await getCompanySettings(companyId); assert.ok(before); const countBefore = await prisma.company.count(); try { await updateCompanySettings(companyId, { ...before, legalName: "Company edit test" }); assert.equal((await getCompanySettings(companyId))?.legalName, "Company edit test"); assert.equal(await prisma.company.count(), countBefore); } finally { await updateCompanySettings(companyId, before); } });

test("Location update è tenant-safe e valida lo slug", async () => { const row = await createLocation(companyId, userId, { code: code("L"), name: "Location edit test" }); locationId = row.id; await updateLocation(companyId, userId, row.id, { slug: row.slug, code: row.code, name: "Location aggiornata", active: true }); assert.equal((await prisma.location.findUniqueOrThrow({ where: { id: row.id } })).name, "Location aggiornata"); await assert.rejects(updateLocation(otherCompanyId, userId, row.id, { slug: row.slug, code: row.code, name: "Cross" }), LocationDomainError); await assert.rejects(updateLocation(companyId, userId, row.id, { slug: "slug-cambiato", code: row.code, name: row.name }), LocationDomainError); });

test("VAT create/edit/deactivate/reactivate e validazione percentuale", async () => { const row = await createVatRate(companyId, userId, { code: code("V"), name: "IVA test", percentage: 22 }); ids.vat.push(row.id); await updateVatRate(companyId, userId, row.id, { code: row.code, name: "IVA aggiornata", percentage: 10, natureCode: "N1" }); assert.equal(Number((await prisma.vatRate.findUniqueOrThrow({ where: { id: row.id } })).percentage), 10); await setVatRateActive(companyId, userId, row.id, false); assert.equal((await prisma.vatRate.findUniqueOrThrow({ where: { id: row.id } })).active, false); await setVatRateActive(companyId, userId, row.id, true); assert.equal((await prisma.vatRate.findUniqueOrThrow({ where: { id: row.id } })).active, true); await assert.rejects(createVatRate(companyId, userId, { code: "BAD", name: "Bad", percentage: 101 }), MasterDataError); });

test("UOM create/edit/deactivate/reactivate", async () => { const row = await createUnit(companyId, userId, { code: code("U"), name: "Unità test", symbol: "pz", precision: 2 }); ids.unit.push(row.id); await updateUnit(companyId, userId, row.id, { code: row.code, name: "Unità aggiornata", symbol: "u", precision: 3 }); await setUnitActive(companyId, userId, row.id, false); assert.equal((await prisma.unitOfMeasure.findUniqueOrThrow({ where: { id: row.id } })).active, false); await setUnitActive(companyId, userId, row.id, true); const updated = await prisma.unitOfMeasure.findUniqueOrThrow({ where: { id: row.id } }); assert.equal(updated.name, "Unità aggiornata"); assert.equal(updated.precision, 3); assert.equal(updated.active, true); });

test("Category create/edit/deactivate/reactivate", async () => { const row = await createCategory(companyId, userId, { code: code("C"), name: "Categoria test" }); ids.category.push(row.id); await updateCategory(companyId, userId, row.id, { code: row.code, name: "Categoria aggiornata" }); await setCategoryActive(companyId, userId, row.id, false); assert.equal((await prisma.itemCategory.findUniqueOrThrow({ where: { id: row.id } })).active, false); await setCategoryActive(companyId, userId, row.id, true); const updated = await prisma.itemCategory.findUniqueOrThrow({ where: { id: row.id } }); assert.equal(updated.name, "Categoria aggiornata"); assert.equal(updated.active, true); });

test("Codici duplicati sono negati per Company", async () => { const suffix = code("D"); const vat = await createVatRate(companyId, userId, { code: suffix, name: "IVA 1", percentage: 1 }); ids.vat.push(vat.id); await assert.rejects(createVatRate(companyId, userId, { code: suffix, name: "IVA 2", percentage: 2 }), MasterDataError); const unit = await createUnit(companyId, userId, { code: suffix, name: "UOM 1", symbol: "x", precision: 0 }); ids.unit.push(unit.id); await assert.rejects(createUnit(companyId, userId, { code: suffix, name: "UOM 2", symbol: "y", precision: 0 }), MasterDataError); const category = await createCategory(companyId, userId, { code: suffix, name: "Cat 1" }); ids.category.push(category.id); await assert.rejects(createCategory(companyId, userId, { code: suffix, name: "Cat 2" }), MasterDataError); });

test("Scritture cross-company sono negate", async () => { const vat = await createVatRate(companyId, userId, { code: code("X"), name: "Cross VAT", percentage: 5 }); ids.vat.push(vat.id); await assert.rejects(updateVatRate(otherCompanyId, userId, vat.id, { code: vat.code, name: "Cross", percentage: 5 }), MasterDataError); await assert.rejects(setVatRateActive(otherCompanyId, userId, vat.id, false), MasterDataError); assert.equal((await getMasterData(otherCompanyId)).vatRates.some((row) => row.id === vat.id), false); });

test("Record referenziati non sono cancellati e dati fiscali/precisione storici sono protetti", async () => { const line = await prisma.businessDocumentLine.findFirstOrThrow({ where: { companyId }, include: { vatRate: true, unitOfMeasure: true } }); const lineCount = await prisma.businessDocumentLine.count({ where: { companyId, vatRateId: line.vatRateId, unitOfMeasureId: line.unitOfMeasureId } }); await assert.rejects(updateVatRate(companyId, userId, line.vatRateId, { code: line.vatRate.code, name: line.vatRate.name, description: line.vatRate.description, percentage: Number(line.vatRate.percentage) + 1, natureCode: line.vatRate.natureCode }), MasterDataError); await assert.rejects(updateUnit(companyId, userId, line.unitOfMeasureId, { code: line.unitOfMeasure.code, name: line.unitOfMeasure.name, description: line.unitOfMeasure.description, symbol: line.unitOfMeasure.symbol, precision: line.unitOfMeasure.precision === 6 ? 5 : line.unitOfMeasure.precision + 1 }), MasterDataError); await setVatRateActive(companyId, userId, line.vatRateId, false); await setUnitActive(companyId, userId, line.unitOfMeasureId, false); assert.equal(await prisma.businessDocumentLine.count({ where: { companyId, vatRateId: line.vatRateId, unitOfMeasureId: line.unitOfMeasureId } }), lineCount); assert.ok(await prisma.vatRate.findUnique({ where: { id: line.vatRateId } })); assert.ok(await prisma.unitOfMeasure.findUnique({ where: { id: line.unitOfMeasureId } })); await setVatRateActive(companyId, userId, line.vatRateId, line.vatRate.active); await setUnitActive(companyId, userId, line.unitOfMeasureId, line.unitOfMeasure.active); });

test("RBAC: admin scrive, manager legge soltanto, altri negati", () => { assert.equal(hasMasterDataCapability(["SUPER_ADMIN"], "write"), true); assert.equal(hasMasterDataCapability(["ADMIN"], "write"), true); assert.equal(hasMasterDataCapability(["MANAGER"], "read"), true); assert.equal(hasMasterDataCapability(["MANAGER"], "write"), false); assert.equal(hasMasterDataCapability(["SALES"], "read"), false); assert.equal(hasMasterDataCapability(["SALES"], "write"), false); assert.equal(canReadLocations(["MANAGER"]), true); assert.equal(canManageLocations(["MANAGER"]), false); assert.equal(canReadLocations(["SALES"]), false); });
