"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireTreasuryContext, type TreasuryCapability } from "@/lib/treasury-access";
import { addBankStatementLine, allocateMovementToSchedule, completeFinancialTransfer, createFinancialAccount, createFinancialTransfer, createManualSchedule, importBankStatement, matchStatementLine, registerCustomerReceipt, registerSupplierPayment, reverseFinancialMovement, unallocateMovement, unmatchStatementLine, updateFinancialAccount } from "@/lib/treasury";
const text = (data: FormData, key: string) => String(data.get(key) ?? "").trim();
const number = (data: FormData, key: string) => Number(text(data, key).replace(",", "."));
const date = (data: FormData, key: string) => new Date(text(data, key) || new Date());
const finish = (path: string) => { revalidatePath("/treasury"); redirect(path); };
const message = (error: unknown) => encodeURIComponent(error instanceof Error ? error.message : "Operazione Treasury non riuscita.");
export async function createAccountAction(data: FormData) { const { companyId, userId } = await requireTreasuryContext("manage"); const row = await createFinancialAccount(companyId, userId, { code: text(data, "code"), name: text(data, "name"), type: text(data, "type") as "BANK" | "CASH" | "CARD" | "PAYPAL" | "OTHER", currency: text(data, "currency") || "EUR", iban: text(data, "iban"), bic: text(data, "bic"), bankName: text(data, "bankName"), openingBalance: number(data, "openingBalance"), allowOverdraft: data.get("allowOverdraft") === "on" }); finish(`/treasury/accounts/${row.id}`); }
export async function registerMovementAction(data: FormData) { const kind = text(data, "kind"); const capability: TreasuryCapability = kind === "receipt" ? "receipt" : "payment"; const { companyId, userId } = await requireTreasuryContext(capability); const input = { financialAccountId: text(data, "financialAccountId"), partnerId: text(data, "partnerId") || null, scheduleId: text(data, "scheduleId") || null, amount: number(data, "amount"), occurredAt: date(data, "occurredAt"), reference: text(data, "reference"), notes: text(data, "notes") }; const row = kind === "receipt" ? await registerCustomerReceipt(companyId, userId, input) : await registerSupplierPayment(companyId, userId, input); finish(`/treasury/movements/${row.id}`); }
export async function movementOperationAction(data: FormData) { const { companyId, userId } = await requireTreasuryContext("manage"); const movementId = text(data, "movementId"); const scheduleId = text(data, "scheduleId"); const operation = text(data, "operation"); if (operation === "reverse") await reverseFinancialMovement(companyId, userId, movementId, text(data, "notes")); else if (operation === "allocate") await allocateMovementToSchedule(companyId, userId, movementId, scheduleId, number(data, "amount")); else if (operation === "unallocate") await unallocateMovement(companyId, userId, movementId, scheduleId); finish(`/treasury/movements/${movementId}`); }
export async function createTransferAction(data: FormData) { const { companyId, userId } = await requireTreasuryContext("transfer"); const row = await createFinancialTransfer(companyId, userId, { sourceAccountId: text(data, "sourceAccountId"), destinationAccountId: text(data, "destinationAccountId"), amount: number(data, "amount"), currency: text(data, "currency") || "EUR", transferDate: date(data, "transferDate") }); finish(`/treasury/transfers/${row.id}`); }
export async function completeTransferAction(data: FormData) { const { companyId, userId } = await requireTreasuryContext("transfer"); const id = text(data, "id"); await completeFinancialTransfer(companyId, userId, id); finish(`/treasury/transfers/${id}`); }
export async function importStatementAction(data: FormData) { const { companyId } = await requireTreasuryContext("reconcile"); const row = await importBankStatement(companyId, text(data, "accountId"), { statementDate: date(data, "statementDate"), openingBalance: number(data, "openingBalance"), closingBalance: number(data, "closingBalance"), lines: [{ transactionDate: date(data, "transactionDate"), amount: number(data, "lineAmount"), description: text(data, "description"), reference: text(data, "reference") }] }); finish(`/treasury/reconciliation/${row.id}`); }
export async function reconciliationAction(data: FormData) { const { companyId } = await requireTreasuryContext("reconcile"); const lineId = text(data, "lineId"); if (text(data, "operation") === "match") await matchStatementLine(companyId, lineId, text(data, "movementId")); else await unmatchStatementLine(companyId, lineId); finish(`/treasury/reconciliation/${text(data, "statementId")}`); }
export async function updateAccountAction(data: FormData) { const { companyId, userId } = await requireTreasuryContext("manage"); const id = text(data, "id"); try { await updateFinancialAccount(companyId, userId, id, { code: text(data, "code"), name: text(data, "name"), type: text(data, "type") as "BANK" | "CASH" | "CARD" | "PAYPAL" | "OTHER", currency: text(data, "currency"), iban: text(data, "iban"), bic: text(data, "bic"), bankName: text(data, "bankName"), active: data.get("active") === "on" }); } catch (error) { redirect(`/treasury/accounts/${id}/edit?error=${message(error)}`); } finish(`/treasury/accounts/${id}?success=Conto aggiornato`); }
export async function createScheduleAction(data: FormData) { const direction = text(data, "direction") === "PAYABLE" ? "PAYABLE" : "RECEIVABLE"; const capability: TreasuryCapability = direction === "RECEIVABLE" ? "receipt" : "payment"; const { companyId, userId } = await requireTreasuryContext(capability); try { await createManualSchedule(companyId, userId, { direction, partnerId: text(data, "partnerId"), dueDate: date(data, "dueDate"), amount: number(data, "amount"), currency: text(data, "currency") || "EUR", paymentMethodId: text(data, "paymentMethodId") || null, paymentTermId: text(data, "paymentTermId") || null, notes: text(data, "notes") }); } catch (error) { redirect(`/treasury/schedules/new?direction=${direction}&error=${message(error)}`); } finish(`${direction === "RECEIVABLE" ? "/treasury/receivables" : "/treasury/payables"}?success=Scadenza creata`); }
export async function addStatementLineAction(data: FormData) { const { companyId } = await requireTreasuryContext("reconcile"); const statementId = text(data, "statementId"); try { await addBankStatementLine(companyId, statementId, { transactionDate: date(data, "transactionDate"), valueDate: text(data, "valueDate") ? date(data, "valueDate") : null, amount: number(data, "amount"), description: text(data, "description"), reference: text(data, "reference") }); } catch (error) { redirect(`/treasury/reconciliation/${statementId}?error=${message(error)}`); } finish(`/treasury/reconciliation/${statementId}?success=Movimento bancario aggiunto`); }
