import { notFound } from "next/navigation";
import { getBankStatement, getTreasuryOptions } from "@/lib/treasury";
import { requireTreasuryContext } from "@/lib/treasury-access";
import { addStatementLineAction, reconciliationAction } from "../../actions";
import { euro, Header, inputClass, Notice } from "../../treasury-ui";

export default async function Page({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; success?: string }> }) {
  const { companyId } = await requireTreasuryContext("reconcile"); const id = (await params).id; const [row, options, query] = await Promise.all([getBankStatement(companyId, id), getTreasuryOptions(companyId), searchParams]); if (!row) notFound();
  return <><Header title={`Estratto ${row.financialAccount.name}`} subtitle={row.status} /><Notice error={query.error} success={query.success} /><div className="rounded border bg-white p-5"><p>Saldo iniziale: {euro(Number(row.openingBalance))}</p><p className="text-xl font-semibold">Saldo finale: {euro(Number(row.closingBalance))}</p></div>{row.status !== "RECONCILED" ? <form action={addStatementLineAction} className="grid gap-3 rounded border bg-white p-5 md:grid-cols-3"><h2 className="font-semibold md:col-span-3">Aggiungi movimento bancario</h2><input name="statementId" type="hidden" value={row.id} /><label>Data operazione<input className={inputClass} name="transactionDate" type="date" required /></label><label>Data valuta<input className={inputClass} name="valueDate" type="date" /></label><label>Importo<input className={inputClass} name="amount" step="0.01" type="number" required /></label><label className="md:col-span-2">Descrizione<input className={inputClass} name="description" required /></label><label>Riferimento<input className={inputClass} name="reference" /></label><button className="rounded bg-slate-900 px-4 py-2 text-white md:col-span-3">Aggiungi movimento bancario</button></form> : <p className="rounded border bg-slate-50 p-4 text-sm text-slate-600">L’estratto riconciliato non accetta nuove righe.</p>}{row.lines.map(line => <div className="rounded border bg-white p-4" key={line.id}><div className="flex justify-between"><span>{line.transactionDate.toLocaleDateString("it-IT")} · {line.description}</span><b>{euro(Number(line.amount))}</b></div>{line.reconciliationStatus === "MATCHED" ? <form action={reconciliationAction}><input name="statementId" type="hidden" value={row.id} /><input name="lineId" type="hidden" value={line.id} /><input name="operation" type="hidden" value="unmatch" /><button className="mt-2 text-red-700">Rimuovi match</button></form> : <form action={reconciliationAction} className="mt-3 flex gap-2"><input name="statementId" type="hidden" value={row.id} /><input name="lineId" type="hidden" value={line.id} /><input name="operation" type="hidden" value="match" /><select className={inputClass} name="movementId" required><option value="">Movimento compatibile</option>{options.movements.filter(m => m.financialAccountId === row.financialAccountId && Number(line.amount) === (m.direction === "IN" ? 1 : -1) * Number(m.amount)).map(m => <option key={m.id} value={m.id}>{m.occurredAt.toLocaleDateString("it-IT")} · {m.reference ?? m.id}</option>)}</select><button className="rounded bg-slate-900 px-4 py-2 text-white">Match</button></form>}</div>)}</>;
}
