import "server-only";

import { Prisma } from "@/generated/prisma/client";
import { executeIdempotent } from "@/lib/idempotency";
import { postInventoryMovementsBatchTx } from "@/lib/inventory";
import { prisma } from "@/lib/prisma";
import { createDraftTx } from "@/lib/documents";
import { preparePurchaseInputTx, activePurchasingSupplierWhere } from "@/lib/purchasing";

export class InventoryProcurementError extends Error { constructor(message:string){super(message);this.name="InventoryProcurementError";} }
const positive=(value:number,label:string)=>{if(!Number.isFinite(value)||value<=0)throw new InventoryProcurementError(`${label} deve essere maggiore di zero.`);return value;};
const nonNegative=(value:number,label:string)=>{if(!Number.isFinite(value)||value<0)throw new InventoryProcurementError(`${label} non può essere negativo.`);return value;};

export type SupplierLinkInput={itemId:string;supplierPartnerId:string;purchaseUomId:string;supplierItemCode?:string|null;preferred?:boolean;packSize:number;minimumOrderQuantity:number;leadTimeDays:number;currency:string;unitCost:number;validFrom?:Date|null;validTo?:Date|null;priority?:number;active?:boolean};
const currencyCodes = new Set<string>(Intl.supportedValuesOf("currency"));
function supplierCurrency(value:string){
  const code=value.trim().toUpperCase();
  if(!currencyCodes.has(code))throw new InventoryProcurementError("Codice valuta supplier mancante o non valido.");
  return code;
}
export async function saveItemSupplier(companyId:string,locationId:string,input:SupplierLinkInput){
  const currency=supplierCurrency(input.currency);
  const packSize=positive(input.packSize,"Il fattore confezione"),moq=positive(input.minimumOrderQuantity,"Il minimo d'ordine"),cost=nonNegative(input.unitCost,"Il costo"),lead=Math.trunc(nonNegative(input.leadTimeDays,"Il lead time"));
  if(input.validFrom&&input.validTo&&input.validTo<input.validFrom)throw new InventoryProcurementError("Intervallo di validità costo non valido.");
  return prisma.$transaction(async tx=>{const[item,supplier,uom,location]=await Promise.all([
    tx.item.findFirst({where:{id:input.itemId,companyId,purchasable:true,active:true,deletedAt:null},select:{id:true}}),
    tx.partner.findFirst({where:{id:input.supplierPartnerId,...activePurchasingSupplierWhere(companyId)},select:{id:true}}),
    tx.unitOfMeasure.findFirst({where:{id:input.purchaseUomId,companyId,active:true,deletedAt:null},select:{id:true}}),
    tx.location.findFirst({where:{id:locationId,companyId,active:true,deletedAt:null},select:{id:true}})]);
    if(!item||!supplier||!uom||!location)throw new InventoryProcurementError("Item, supplier, UOM o Location non validi per la Company.");
    if(input.preferred)await tx.itemSupplier.updateMany({where:{companyId,locationId,itemId:item.id,preferred:true,active:true,supplierPartnerId:{not:supplier.id}},data:{preferred:false}});
    const data={supplierItemCode:input.supplierItemCode?.trim()||null,preferred:Boolean(input.preferred),purchaseUomId:uom.id,packSize,minimumOrderQuantity:moq,leadTimeDays:lead,currency,unitCost:cost,validFrom:input.validFrom??null,validTo:input.validTo??null,priority:Math.trunc(input.priority??0),active:input.active??true};
    return tx.itemSupplier.upsert({where:{companyId_locationId_itemId_supplierPartnerId:{companyId,locationId,itemId:item.id,supplierPartnerId:supplier.id}},create:{companyId,locationId,itemId:item.id,supplierPartnerId:supplier.id,...data},update:data});
  },{isolationLevel:"Serializable"});
}

export type OpeningRow={itemCode:string;warehouseCode:string;binCode?:string;quantity:number;uomCode:string;unitCost:number;lotCode?:string;serialCode?:string;expiryDate?:string;note?:string};
const formula=/^[=+@]/;
function splitCsvLine(line:string){const out:string[]=[],re=/(?:^|,)("(?:[^"]|"")*"|[^,]*)/g;let m;while((m=re.exec(line)))out.push(m[1].replace(/^"|"$/g,"").replace(/""/g,'"').trim());return out;}
export function parseOpeningCsv(csv:string){if(csv.includes("\0"))throw new InventoryProcurementError("File eseguibile o binario non accettato.");const lines=csv.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean);if(lines.length<2)throw new InventoryProcurementError("CSV vuoto.");const expected=["itemCode","warehouseCode","binCode","quantity","uomCode","unitCost","lotCode","serialCode","expiryDate","note"],header=splitCsvLine(lines[0]);if(expected.some((x,i)=>header[i]!==x))throw new InventoryProcurementError(`Header CSV atteso: ${expected.join(",")}`);return lines.slice(1).map((line,index)=>{const c=splitCsvLine(line);if(c.some(value=>formula.test(value)))throw new InventoryProcurementError(`Riga ${index+2}: formule non accettate.`);return{itemCode:c[0],warehouseCode:c[1],binCode:c[2]||undefined,quantity:Number(c[3]),uomCode:c[4],unitCost:Number(c[5]),lotCode:c[6]||undefined,serialCode:c[7]||undefined,expiryDate:c[8]||undefined,note:c[9]||undefined} satisfies OpeningRow;});}
async function previewOpeningTx(tx:Prisma.TransactionClient,companyId:string,locationId:string,rows:OpeningRow[]){const errors:string[][]=rows.map(()=>[]);const[items,warehouses,uoms]=await Promise.all([tx.item.findMany({where:{companyId,active:true,deletedAt:null,stockManaged:true},select:{id:true,code:true,unitOfMeasureId:true,trackLots:true,trackSerials:true,trackExpiration:true}}),tx.warehouse.findMany({where:{companyId,locationId,active:true,deletedAt:null},include:{bins:{where:{active:true,deletedAt:null}}}}),tx.unitOfMeasure.findMany({where:{companyId,active:true,deletedAt:null},select:{id:true,code:true}})]);const im=new Map(items.map(x=>[x.code,x])),wm=new Map(warehouses.map(x=>[x.code,x])),um=new Map(uoms.map(x=>[x.code,x]));const resolved=rows.map((r,i)=>{const item=im.get(r.itemCode),warehouse=wm.get(r.warehouseCode),uom=um.get(r.uomCode),bin=r.binCode?warehouse?.bins.find(x=>x.code===r.binCode):undefined;if(!item)errors[i].push("Item non valido");if(!warehouse)errors[i].push("Warehouse non valido");if(r.binCode&&!bin)errors[i].push("Bin non valido");if(!uom||uom.id!==item?.unitOfMeasureId)errors[i].push("UOM stock non valida");if(!Number.isFinite(r.quantity)||r.quantity<=0)errors[i].push("Quantità non valida");if(!Number.isFinite(r.unitCost)||r.unitCost<0)errors[i].push("Costo non valido");if(item?.trackLots&&!r.lotCode)errors[i].push("Lotto obbligatorio");if(item?.trackSerials&&!r.serialCode)errors[i].push("Seriale obbligatorio");if(item?.trackSerials&&r.quantity!==1)errors[i].push("Quantità seriale deve essere 1");if(item?.trackExpiration&&!r.expiryDate)errors[i].push("Scadenza obbligatoria");if(r.expiryDate&&Number.isNaN(new Date(r.expiryDate).getTime()))errors[i].push("Scadenza non valida");return{row:r,item,warehouse,uom,bin};});return{valid:errors.every(x=>!x.length),errors,resolved};}
export async function previewOpening(companyId:string,locationId:string,rows:OpeningRow[]){return previewOpeningTx(prisma,companyId,locationId,rows);}

export async function confirmOpening(companyId:string,locationId:string,userId:string,idempotencyKey:string,rows:OpeningRow[]){return executeIdempotent(companyId,"InventoryOpeningBatch",locationId+":"+idempotencyKey,async tx=>{const preview=await previewOpeningTx(tx,companyId,locationId,rows);if(!preview.valid)throw new InventoryProcurementError(preview.errors.map((e,i)=>e.length?`Riga ${i+2}: ${e.join(", ")}`:"").filter(Boolean).join("; "));const movements=[];for(const x of preview.resolved){let lotId:string|undefined,serialId:string|undefined;if(x.row.lotCode){const lot=await tx.inventoryLot.upsert({where:{companyId_itemId_lotNumber:{companyId,itemId:x.item!.id,lotNumber:x.row.lotCode}},create:{companyId,locationId,itemId:x.item!.id,lotNumber:x.row.lotCode,expirationDate:x.row.expiryDate?new Date(x.row.expiryDate):null},update:{expirationDate:x.row.expiryDate?new Date(x.row.expiryDate):undefined,active:true}});if(lot.locationId!==locationId)throw new InventoryProcurementError("Lotto già esistente in altra Location.");lotId=lot.id;}if(x.row.serialCode){const serial=await tx.inventorySerial.upsert({where:{companyId_serialNumber:{companyId,serialNumber:x.row.serialCode}},create:{companyId,locationId,itemId:x.item!.id,serialNumber:x.row.serialCode},update:{}});if(serial.locationId!==locationId||serial.itemId!==x.item!.id)throw new InventoryProcurementError("Seriale già associato altrove.");serialId=serial.id;}movements.push({warehouseId:x.warehouse!.id,locationId,binId:x.bin?.id,itemId:x.item!.id,movementType:"OPENING" as const,quantity:x.row.quantity,unitOfMeasureId:x.uom!.id,lotId,serialId,unitCost:x.row.unitCost,referenceType:"InventoryOpeningBatch",referenceId:idempotencyKey,reason:"Carico iniziale",note:x.row.note});}const posted=await postInventoryMovementsBatchTx(tx,companyId,userId,movements);await tx.auditLog.create({data:{companyId,userId,locationId,action:"INVENTORY_OPENING_POSTED",entityType:"InventoryMovementBatch",entityId:posted[0]?.id,metadata:{idempotencyKey,lineCount:posted.length}}});return{aggregateId:posted[0]?.id??"",movementIds:posted.map(x=>x.id),lineCount:posted.length};},{aggregateType:"InventoryMovementBatch",timeout:30000});}

export async function saveWarehouseItemPolicy(companyId:string,locationId:string,input:{warehouseId:string;itemId:string;minimumStock?:number|null;reorderPoint:number;targetStock?:number|null;active?:boolean}){const reorder=nonNegative(input.reorderPoint,"Il punto di riordino"),minimum=input.minimumStock==null?null:nonNegative(input.minimumStock,"Lo stock minimo"),target=input.targetStock==null?null:nonNegative(input.targetStock,"Lo stock target");if(target!==null&&target<reorder)throw new InventoryProcurementError("Lo stock target deve essere almeno pari al punto di riordino.");const[warehouse,item]=await Promise.all([prisma.warehouse.findFirst({where:{id:input.warehouseId,companyId,locationId,active:true,deletedAt:null}}),prisma.item.findFirst({where:{id:input.itemId,companyId,stockManaged:true,active:true,deletedAt:null}})]);if(!warehouse||!item)throw new InventoryProcurementError("Warehouse o Item non valido per la Location.");return prisma.warehouseItemPolicy.upsert({where:{companyId_warehouseId_itemId:{companyId,warehouseId:warehouse.id,itemId:item.id}},create:{companyId,locationId,warehouseId:warehouse.id,itemId:item.id,minimumStock:minimum,reorderPoint:reorder,targetStock:target,active:input.active??true},update:{minimumStock:minimum,reorderPoint:reorder,targetStock:target,active:input.active??true}});}
export function roundPurchaseQuantity(requiredStock:number,packSize:number,moq:number){return Math.ceil(Math.max(requiredStock/positive(packSize,"Il pack size"),positive(moq,"Il MOQ")));}
export async function getReorderProposals(companyId:string,locationId:string,now=new Date()){return getReorderProposalsTx(prisma,companyId,locationId,now);}
async function getReorderProposalsTx(tx:Prisma.TransactionClient,companyId:string,locationId:string,now=new Date()){const rows=await tx.warehouseItemPolicy.findMany({where:{companyId,locationId,active:true,
warehouse:{companyId,locationId,active:true,deletedAt:null,location:{companyId,id:locationId,active:true,deletedAt:null}},
item:{companyId,active:true,deletedAt:null,purchasable:true,stockManaged:true,unitOfMeasure:{companyId,active:true,deletedAt:null}}},
include:{warehouse:true,item:{include:{stockBalances:{where:{companyId,locationId}},suppliers:{where:{companyId,locationId,active:true,preferred:true,supplier:activePurchasingSupplierWhere(companyId),purchaseUom:{companyId,active:true,deletedAt:null}},include:{supplier:true,purchaseUom:true}}}}}});return rows.flatMap(policy=>{const available=Number(policy.item.stockBalances.find(x=>x.warehouseId===policy.warehouseId)?.quantity??0),reorder=Number(policy.reorderPoint);if(available>reorder)return[];const supplier=policy.item.suppliers.find(x=>(!x.validFrom||x.validFrom<=now)&&(!x.validTo||x.validTo>=now));if(!supplier)return[];const target=Number(policy.targetStock??policy.minimumStock??policy.reorderPoint),needed=Math.max(target-available,0),pack=Number(supplier.packSize),moq=Number(supplier.minimumOrderQuantity),purchaseQty=roundPurchaseQuantity(needed,pack,moq);return[{policyId:policy.id,itemId:policy.itemId,itemCode:policy.item.code,itemName:policy.item.name,warehouseId:policy.warehouseId,warehouseCode:policy.warehouse.code,available,reorderPoint:reorder,targetStock:target,supplierId:supplier.supplierPartnerId,supplierName:supplier.supplier.displayName??supplier.supplier.name,purchaseUomId:supplier.purchaseUomId,purchaseUom:supplier.purchaseUom.symbol,packSize:pack,moq,leadTimeDays:supplier.leadTimeDays,unitCost:Number(supplier.unitCost),currency:supplier.currency,suggestedQty:purchaseQty,estimatedCost:purchaseQty*Number(supplier.unitCost)}];});}
export async function createPurchaseOrdersFromReorder(companyId:string,locationId:string,userId:string,idempotencyKey:string,policyIds:string[]){return executeIdempotent(companyId,"ReorderPurchaseProposal",locationId+":"+idempotencyKey,async tx=>{const proposals=(await getReorderProposalsTx(tx,companyId,locationId)).filter(x=>policyIds.includes(x.policyId));if(!proposals.length||proposals.length!==new Set(policyIds).size)throw new InventoryProcurementError("Nessuna proposta valida selezionata.");// Reorder currently feeds an EUR-only purchasing UI and unconverted
// Inventory costs. Never reinterpret supplier amounts or assume an FX rate.
const company=await tx.company.findUnique({where:{id:companyId},select:{currency:true}});
if(company?.currency!=="EUR")throw new InventoryProcurementError("Riordino non disponibile: il flusso supporta solo Company con valuta EUR, senza FX.");
for(const proposal of proposals){
  const currency=supplierCurrency(proposal.currency);
  if(proposal.currency!==currency||currency!=="EUR")throw new InventoryProcurementError("Riordino non disponibile: valuta supplier diversa da EUR; nessuna conversione FX applicata.");
}
const series=await tx.documentSeries.findFirst({where:{companyId,locationId,documentType:"PURCHASE_ORDER",active:true},orderBy:{code:"asc"}});if(!series)throw new InventoryProcurementError("Serie ordine fornitore mancante.");const grouped=new Map<string,typeof proposals>();for(const p of proposals)grouped.set(p.supplierId,[...(grouped.get(p.supplierId)??[]),p]);const ids=[];for(const[supplierId,group]of grouped){const items=await tx.item.findMany({where:{companyId,id:{in:group.map(x=>x.itemId)}},select:{id:true,name:true,vatRateId:true}});const map=new Map(items.map(x=>[x.id,x]));if(items.some(x=>!x.vatRateId))throw new InventoryProcurementError("IVA mancante su Item proposto.");const prepared=await preparePurchaseInputTx(tx,companyId,{partnerId:supplierId,documentDate:new Date(),currency:"EUR",warehouseId:group[0].warehouseId,locationId,internalNotes:`Reorder ${idempotencyKey}`,lines:group.map(p=>({itemId:p.itemId,description:map.get(p.itemId)!.name,quantity:p.suggestedQty,unitOfMeasureId:p.purchaseUomId,unitPrice:p.unitCost,vatRateId:map.get(p.itemId)!.vatRateId!,warehouseId:p.warehouseId,notes:`Pack ${p.packSize}; MOQ ${p.moq}`}))});const doc=await createDraftTx(tx,companyId,userId,{...prepared,seriesId:series.id});ids.push(doc.id);}await tx.auditLog.create({data:{companyId,userId,locationId,action:"REORDER_PURCHASE_ORDERS_CREATED",entityType:"BusinessDocument",metadata:{idempotencyKey,documentIds:ids}}});return{aggregateId:ids[0],documentIds:ids};},{aggregateType:"BusinessDocument",timeout:30000});}
