import "server-only";
import { prisma } from "@/lib/prisma";
import { postInventoryMovementsBatchTx, type MovementInput } from "@/lib/inventory";
import { executeIdempotent } from "@/lib/idempotency";
import { emitRestaurantEvent, emitRestaurantEventTx, RestaurantDomainError } from "@/lib/restaurant";

export async function sendOrderToKitchen(companyId:string, locationId:string, orderId:string) {
  const order=await prisma.restaurantOrder.findFirst({where:{id:orderId,companyId,locationId,status:{in:["OPEN","SENT","IN_PROGRESS"]}},include:{lines:{where:{status:"NEW"},include:{item:true}}}});
  if(!order||!order.lines.length) throw new RestaurantDomainError("Nessuna nuova riga da inviare.");
  for(const line of order.lines){
    const assignment=await prisma.kitchenStationAssignment.findFirst({where:{companyId,active:true,station:{locationId:order.locationId,active:true},OR:[{itemId:line.itemId},{itemCategoryId:line.item.categoryId}]},orderBy:[{itemId:"desc"},{priority:"desc"}]});
    if(!assignment) throw new RestaurantDomainError(`Nessuna stazione configurata per ${line.item.name}.`);
    let ticket=await prisma.kitchenTicket.findFirst({where:{companyId,locationId,orderId:order.id,kitchenStationId:assignment.kitchenStationId,status:"NEW",lines:{none:{}}}});
    ticket??=await prisma.kitchenTicket.create({data:{companyId,locationId:order.locationId,orderId:order.id,kitchenStationId:assignment.kitchenStationId}});
    await prisma.kitchenTicketLine.create({data:{companyId,locationId,ticketId:ticket.id,orderLineId:line.id}});
    await prisma.restaurantOrderLine.update({where:{id:line.id},data:{status:"SENT",sentAt:new Date()}});
    await emitRestaurantEvent(companyId,"KitchenTicketCreated","KitchenTicket",ticket.id,{orderLineId:line.id});
  }
  await prisma.restaurantOrder.update({where:{id:order.id},data:{status:"SENT"}}); await emitRestaurantEvent(companyId,"RestaurantOrderSentToKitchen","RestaurantOrder",order.id,{}); return {id:order.id};
}
export async function advanceKitchenLine(companyId:string,locationId:string,userId:string,lineId:string,status:"IN_PREPARATION"|"READY"|"SERVED"){
  if(status==="SERVED") return serveRestaurantOrderLine(companyId,locationId,userId,lineId,`${companyId}:${lineId}:serve`);
  const line=await prisma.restaurantOrderLine.findFirst({where:{id:lineId,companyId,locationId},include:{order:true,item:{include:{recipeComponents:{where:{deletedAt:null},include:{componentItem:true}}}}}});if(!line)throw new RestaurantDomainError("Riga non trovata.");
  const data=status==="IN_PREPARATION"?{status,startedAt:new Date()}:{status,readyAt:new Date()};await prisma.restaurantOrderLine.update({where:{id:line.id},data});await prisma.kitchenTicketLine.updateMany({where:{companyId,locationId,orderLineId:line.id},data:{status}});
  await emitRestaurantEvent(companyId,status==="READY"?"KitchenItemReady":"KitchenPreparationStarted","RestaurantOrderLine",line.id,{status});return{id:line.id};
}
export async function serveRestaurantOrderLine(companyId:string,locationId:string,userId:string,lineId:string,idempotencyKey:string,lotSelections:Record<string,string>={}){
  return executeIdempotent(companyId,"RestaurantOrderLineServe",locationId + ":" + idempotencyKey,async tx=>{
    const line=await tx.restaurantOrderLine.findFirst({where:{id:lineId,companyId,locationId,status:{in:["READY","SERVED"]}},include:{order:true,item:{include:{recipeComponents:{where:{deletedAt:null},include:{componentItem:true,unitOfMeasure:{select:{precision:true}}}}}},variant:{include:{recipeImpacts:{include:{componentItem:true,unitOfMeasure:{select:{precision:true}}}}}},modifiers:{include:{modifier:{include:{recipeImpacts:{include:{componentItem:true,unitOfMeasure:{select:{precision:true}}}}}}}}}});
    if(!line)throw new RestaurantDomainError("Solo una riga pronta può essere servita.");if(line.status==="SERVED")return{aggregateId:line.id,orderLineId:line.id,movementIds:[]};
    type Component={itemId:string;unitOfMeasureId:string;quantity:number;precision:number;item:{name:string;trackLots:boolean;trackSerials:boolean}};const components=new Map<string,Component>();
    const add=(componentItemId:string,unitOfMeasureId:string,quantity:number,precision:number,item:Component["item"])=>{const current=components.get(componentItemId);if(current&&current.unitOfMeasureId!==unitOfMeasureId)throw new RestaurantDomainError("Unità di misura incoerente negli impatti ricetta per " + item.name + ".");components.set(componentItemId,{itemId:componentItemId,unitOfMeasureId,quantity:(current?.quantity??0)+quantity,precision,item});};
    if(line.item.type==="RECIPE")for(const component of line.item.recipeComponents)add(component.componentItemId,component.unitOfMeasureId,Number(component.quantity)*(1+Number(component.wastePercentage||0)/100),component.unitOfMeasure.precision,component.componentItem);
    const impacts=[...(line.variant?.recipeImpacts??[]),...line.modifiers.flatMap(selection=>selection.modifier?.recipeImpacts??[])];for(const impact of impacts)add(impact.componentItemId,impact.unitOfMeasureId,Number(impact.quantityDelta),impact.unitOfMeasure.precision,impact.componentItem);
    for(const component of components.values())if(component.quantity<0)throw new RestaurantDomainError("L impatto ricetta rende negativo il consumo di " + component.item.name + ".");
    const activeComponents=[...components.values()].filter(component=>component.quantity>0);const warehouse=activeComponents.length?await tx.warehouse.findFirst({where:{companyId,locationId:line.order.locationId,active:true,deletedAt:null},include:{bins:{where:{active:true,deletedAt:null},take:1}}}):null;if(activeComponents.length&&!warehouse)throw new RestaurantDomainError("Magazzino Restaurant non configurato.");
    const inputs:MovementInput[]=activeComponents.map(component=>{const lotId=lotSelections[component.itemId];if((component.item.trackLots||component.item.trackSerials)&&!lotId)throw new RestaurantDomainError("Lotto o seriale obbligatorio per " + component.item.name + ".");const precision=Math.min(3,component.precision),factor=10**precision,quantity=Math.round((Number(line.quantity)*component.quantity+Number.EPSILON)*factor)/factor;return{warehouseId:warehouse!.id,binId:warehouse!.bins[0]?.id,itemId:component.itemId,movementType:"CONSUMPTION",quantity,unitOfMeasureId:component.unitOfMeasureId,lotId:component.item.trackLots?lotId:null,serialId:component.item.trackSerials?lotId:null,referenceType:"RestaurantOrderLine",referenceId:line.id,reason:"Consumo ricetta servita"};});
    const movements=inputs.length?await postInventoryMovementsBatchTx(tx,companyId,userId,inputs):[];for(let index=0;index<inputs.length;index++){const input=inputs[index];await tx.recipeConsumption.create({data:{companyId,locationId:line.order.locationId,orderId:line.order.id,orderLineId:line.id,recipeItemId:line.item.id,componentItemId:input.itemId,inventoryMovementId:movements[index].id,quantity:Number(input.quantity)}})}
    await tx.restaurantOrderLine.update({where:{id:line.id},data:{status:"SERVED",servedAt:new Date()}});await tx.kitchenTicketLine.updateMany({where:{companyId,locationId,orderLineId:line.id},data:{status:"COMPLETED"}});await emitRestaurantEventTx(tx,companyId,"RestaurantOrderLineServed","RestaurantOrderLine",line.id,{movementIds:movements.map(m=>m.id)});if(movements.length)await emitRestaurantEventTx(tx,companyId,"RecipeInventoryConsumed","RestaurantOrderLine",line.id,{movementIds:movements.map(m=>m.id)});return{aggregateId:line.id,orderLineId:line.id,movementIds:movements.map(m=>m.id)};
  },{aggregateType:"RestaurantOrderLine",aggregateId:lineId});
}
export async function reverseRecipeConsumption(companyId:string,locationId:string,userId:string,lineId:string,idempotencyKey=`${companyId}:${lineId}:reverse-consumption`){return executeIdempotent(companyId,"RestaurantRecipeConsumptionReverse",locationId + ":" + idempotencyKey,async tx=>{const rows=await tx.recipeConsumption.findMany({where:{companyId,locationId,orderLineId:lineId},include:{inventoryMovement:true}});const inputs:MovementInput[]=rows.map(row=>({warehouseId:row.inventoryMovement.warehouseId,binId:row.inventoryMovement.binId,itemId:row.componentItemId,movementType:"ADJUSTMENT_IN",quantity:Number(row.quantity),unitOfMeasureId:row.inventoryMovement.unitOfMeasureId,lotId:row.inventoryMovement.lotId,serialId:row.inventoryMovement.serialId,unitCost:Number(row.inventoryMovement.unitCost??0),referenceType:"RestaurantOrderLineReversal",referenceId:lineId,reason:"Storno compensativo completo consumo Restaurant"}));const movements=await postInventoryMovementsBatchTx(tx,companyId,userId,inputs);await emitRestaurantEventTx(tx,companyId,"RecipeInventoryConsumptionReversed","RestaurantOrderLine",lineId,{movementIds:movements.map(m=>m.id)});return{aggregateId:lineId,count:movements.length,movementIds:movements.map(m=>m.id)}})}
export const getKitchen= (companyId:string,locationId:string,stationId?:string)=>prisma.kitchenTicket.findMany({where:{companyId,locationId,kitchenStationId:stationId,status:{notIn:["COMPLETED","CANCELLED"]}},include:{station:true,order:true,lines:{include:{orderLine:{include:{item:true,modifiers:true}}}}},orderBy:{createdAt:"asc"}});
