import "server-only";
import { prisma } from "@/lib/prisma";
import { createDraftTx, confirmDocumentTx, postDocumentTx } from "@/lib/documents";
import { allocateMovementToScheduleTx, registerCustomerReceiptTx } from "@/lib/treasury";
import { executeIdempotent } from "@/lib/idempotency";
import { emitRestaurantEvent, emitRestaurantEventTx, RestaurantDomainError } from "@/lib/restaurant";
import { restaurantFiscalAdapter } from "@/lib/restaurant-fiscal-adapter";

export async function openOrder(companyId:string,userId:string,input:{locationId:string;tableId?:string|null;reservationId?:string|null;partnerId?:string|null;guestCount:number;serviceType:"DINE_IN"|"TAKEAWAY"|"DELIVERY"|"EVENT";notes?:string}){
  if(input.guestCount<1)throw new RestaurantDomainError("Numero coperti non valido.");if(input.tableId){const table=await prisma.restaurantTable.findFirst({where:{id:input.tableId,companyId,locationId:input.locationId,active:true,deletedAt:null,status:{notIn:["OUT_OF_SERVICE","OCCUPIED"]}}});if(!table)throw new RestaurantDomainError("Tavolo non disponibile.");}
  const row=await prisma.restaurantOrder.create({data:{companyId,locationId:input.locationId,code:`ORD-${Date.now().toString(36).toUpperCase()}`,tableId:input.tableId||null,reservationId:input.reservationId||null,partnerId:input.partnerId||null,guestCount:input.guestCount,serviceType:input.serviceType,notes:input.notes,createdById:userId,updatedById:userId},select:{id:true}});if(input.tableId)await prisma.restaurantTable.update({where:{id:input.tableId},data:{status:"OCCUPIED"}});await emitRestaurantEvent(companyId,"RestaurantOrderOpened","RestaurantOrder",row.id,{});return row;
}
export async function addOrderLine(companyId:string,orderId:string,input:{itemId:string;quantity:number;courseNumber?:number;notes?:string;kitchenNotes?:string}){const order=await prisma.restaurantOrder.findFirst({where:{id:orderId,companyId,status:{notIn:["CLOSED","CANCELLED"]}}});const item=await prisma.item.findFirst({where:{id:input.itemId,companyId,sellable:true,active:true,deletedAt:null},include:{restaurantMenuItems:{where:{available:true},orderBy:{createdAt:"desc"},take:1}}});if(!order||!item||!item.vatRateId||input.quantity<=0)throw new RestaurantDomainError("Ordine o Item non valido.");const line=await prisma.restaurantOrderLine.create({data:{companyId,orderId,itemId:item.id,quantity:input.quantity,unitPrice:item.restaurantMenuItems[0]?.priceOverride??item.salePrice??0,vatRateId:item.vatRateId,courseNumber:input.courseNumber,notes:input.notes,kitchenNotes:input.kitchenNotes},select:{id:true}});await emitRestaurantEvent(companyId,"RestaurantOrderLineAdded","RestaurantOrder",orderId,{lineId:line.id});return line;}
export async function cancelNewLine(companyId:string,lineId:string){const result=await prisma.restaurantOrderLine.updateMany({where:{id:lineId,companyId,status:"NEW"},data:{status:"CANCELLED",cancelledAt:new Date()}});if(!result.count)throw new RestaurantDomainError("Solo una riga NEW può essere annullata.");return{id:lineId};}
export async function transferOrderTable(companyId:string,orderId:string,tableId:string){return prisma.$transaction(async tx=>{const order=await tx.restaurantOrder.findFirst({where:{id:orderId,companyId,status:{notIn:["CLOSED","CANCELLED"]}}});const table=await tx.restaurantTable.findFirst({where:{id:tableId,companyId,locationId:order?.locationId,status:"AVAILABLE",deletedAt:null}});if(!order||!table)throw new RestaurantDomainError("Trasferimento tavolo non consentito.");if(order.tableId)await tx.restaurantTable.update({where:{id:order.tableId},data:{status:"AVAILABLE"}});await tx.restaurantTable.update({where:{id:table.id},data:{status:"OCCUPIED"}});await tx.restaurantOrder.update({where:{id:order.id},data:{tableId:table.id}});return{id:order.id};});}
export type RestaurantPaymentInput={financialAccountId:string;paymentMethod:"CASH"|"CARD"|"BANK"|"OTHER";amount:number};
export async function closeRestaurantOrderAtomic(companyId:string,userId:string,orderId:string,idempotencyKey:string,input:{seriesId:string;invoice:boolean;payments:RestaurantPaymentInput[]}) {
  const result=await executeIdempotent(companyId,"RestaurantOrderClose",idempotencyKey,async tx=>{
    const order=await tx.restaurantOrder.findFirst({where:{id:orderId,companyId,status:{not:"CANCELLED"}},include:{lines:{where:{status:{not:"CANCELLED"}},include:{item:true}},document:true}});
    if(!order||!order.partnerId||!order.lines.length)throw new RestaurantDomainError("Cliente e righe sono necessari per chiudere il conto.");
    if(order.status==="CLOSED")return{aggregateId:order.id,orderId:order.id,documentId:order.documentId!,movementIds:[],paymentStatus:"PAID",total:Number(order.document?.total??0)};
    if(order.lines.some(line=>line.status!=="SERVED"))throw new RestaurantDomainError("Tutte le righe devono essere servite.");
    let documentId=order.documentId;let total=Number(order.document?.total??0);
    if(!documentId){const series=await tx.documentSeries.findFirst({where:{id:input.seriesId,companyId,active:true,documentType:input.invoice?"SALES_INVOICE":"SALES_RECEIPT"}});if(!series)throw new RestaurantDomainError(input.invoice?"Selezionare una serie fattura.":"Selezionare la serie conto Restaurant.");const doc=await createDraftTx(tx,companyId,userId,{seriesId:series.id,partnerId:order.partnerId,documentDate:new Date(),currency:"EUR",locationId:order.locationId,lines:order.lines.map(line=>({itemId:line.itemId,description:line.item.name,quantity:Number(line.quantity),unitOfMeasureId:line.item.unitOfMeasureId!,unitPrice:Number(line.unitPrice),vatRateId:line.vatRateId}))});await confirmDocumentTx(tx,companyId,userId,order.locationId,doc.id);await postDocumentTx(tx,companyId,userId,order.locationId,doc.id);const posted=await tx.businessDocument.findUniqueOrThrow({where:{id:doc.id},select:{total:true}});documentId=doc.id;total=Number(posted.total);await emitRestaurantEventTx(tx,companyId,"RestaurantBillCreated","RestaurantOrder",order.id,{documentId,total,fiscal:false});}
    const alreadyPaid=Number((await tx.financialMovement.aggregate({where:{companyId,documentId,movementType:"CUSTOMER_RECEIPT",reversalOfId:null,reversals:{none:{}}},_sum:{amount:true}}))._sum.amount??0);if(input.payments.some(payment=>!Number.isFinite(Number(payment.amount))||Number(payment.amount)<=0))throw new RestaurantDomainError("Gli importi di pagamento devono essere positivi.");const requested=input.payments.reduce((sum,payment)=>sum+Number(payment.amount),0);const residual=Math.max(0,total-alreadyPaid);if(!Number.isFinite(requested)||requested>residual+0.001)throw new RestaurantDomainError("Il pagamento supera il residuo del conto.");
    const schedules=await tx.paymentSchedule.findMany({where:{companyId,documentId,status:{in:["OPEN","PARTIALLY_PAID","OVERDUE"]},deletedAt:null},orderBy:[{dueDate:"asc"},{installmentNumber:"asc"}]});const scheduleResiduals=new Map(schedules.map(schedule=>[schedule.id,Number(schedule.residualAmount)]));
    const movementIds:string[]=[];for(const payment of input.payments){if(payment.amount<=0)continue;const movement=await registerCustomerReceiptTx(tx,companyId,userId,{financialAccountId:payment.financialAccountId,partnerId:order.partnerId,documentId,amount:payment.amount,occurredAt:new Date(),reference:`RestaurantOrder:${order.id}`,notes:payment.paymentMethod});movementIds.push(movement.id);let allocatable=Number(payment.amount);for(const schedule of schedules){if(allocatable<=0)break;const residualAmount=scheduleResiduals.get(schedule.id)??0;const allocation=Math.min(allocatable,residualAmount);if(allocation>0){await allocateMovementToScheduleTx(tx,companyId,userId,movement.id,schedule.id,allocation);scheduleResiduals.set(schedule.id,residualAmount-allocation);allocatable-=allocation;}}await emitRestaurantEventTx(tx,companyId,"RestaurantPaymentRegistered","RestaurantOrder",order.id,{movementId:movement.id,amount:payment.amount,method:payment.paymentMethod});}
    const nextPaid=alreadyPaid+requested;const paid=Math.abs(total-nextPaid)<0.001;await tx.restaurantOrder.update({where:{id:order.id},data:{documentId,paymentStatus:paid?"PAID":nextPaid>0?"PARTIALLY_PAID":"UNPAID",status:paid?"CLOSED":order.status,closedAt:paid?new Date():null}});if(paid&&order.tableId)await tx.restaurantTable.update({where:{id:order.tableId},data:{status:"DIRTY"}});if(paid)await emitRestaurantEventTx(tx,companyId,"RestaurantOrderClosed","RestaurantOrder",order.id,{documentId,total});return{aggregateId:order.id,orderId:order.id,documentId,movementIds,paymentStatus:paid?"PAID":"PARTIALLY_PAID",total};
  },{aggregateType:"RestaurantOrder",aggregateId:orderId,timeout:30000});
  if(result.documentId)await restaurantFiscalAdapter.transmit({orderId,documentId:result.documentId,total:result.total});return result;
}
export async function closeOrder(companyId:string,userId:string,orderId:string,idempotencyKey:string,input:{seriesId:string;financialAccountId:string;paymentMethod:"CASH"|"CARD"|"BANK"|"OTHER";amount:number;invoice:boolean}){return closeRestaurantOrderAtomic(companyId,userId,orderId,idempotencyKey,{seriesId:input.seriesId,invoice:input.invoice,payments:input.amount>0?[{financialAccountId:input.financialAccountId,paymentMethod:input.paymentMethod,amount:input.amount}]:[]})}
export const getOrders=(companyId:string)=>prisma.restaurantOrder.findMany({where:{companyId},include:{table:true,partner:true,_count:{select:{lines:true}}},orderBy:{openedAt:"desc"}});
export const getOrder=(companyId:string,id:string)=>prisma.restaurantOrder.findFirst({where:{id,companyId},include:{table:true,partner:true,document:true,lines:{include:{item:true,modifiers:true},orderBy:{createdAt:"asc"}}}});
