import "server-only";

import { randomUUID } from "node:crypto";
import { Prisma, type DocumentType, type FinancialMovementDirection, type FinancialMovementType, type PaymentScheduleDirection } from "@/generated/prisma/client";
import { MODULE_CODES } from "@/lib/module-catalog";
import { prisma } from "@/lib/prisma";

export class TreasuryDomainError extends Error { constructor(message: string) { super(message); this.name = "TreasuryDomainError"; } }
type Tx = Prisma.TransactionClient;
const money = (value: number) => Math.round((value + Number.EPSILON) * 100) / 100;
const positive = (value: number, label = "Importo") => { if (!Number.isFinite(value) || value <= 0) throw new TreasuryDomainError(`${label} non valido.`); return money(value); };
async function emit(tx: Tx, companyId: string, eventType: string, aggregateType: string, aggregateId: string, payload: Prisma.InputJsonValue = {}) { await tx.domainEvent.create({ data: { companyId, eventType, aggregateType, aggregateId, payload, occurredAt: new Date() } }); }
async function moduleEnabled(tx: Tx, companyId: string, code: string) { return Boolean(await tx.companyModule.findFirst({ where: { companyId, enabled: true, moduleDefinition: { code, status: "AVAILABLE" } }, select: { id: true } })); }

export type ScheduleInput = { locationId: string; partnerId: string; direction: PaymentScheduleDirection; dueDate: Date; amount: number; currency?: string; paymentMethodId?: string | null; paymentTermId?: string | null; documentId?: string | null; documentType?: DocumentType | null; notes?: string | null };
export async function createManualSchedule(companyId: string, userId: string, input: ScheduleInput) { return prisma.$transaction(async (tx) => createSchedule(tx, companyId, userId, input)); }
async function createSchedule(tx: Tx, companyId: string, userId: string, input: ScheduleInput, installmentNumber = 1) {
  const amount = positive(input.amount);
  const partner = await tx.partner.findFirst({ where: { id: input.partnerId, companyId, active: true, deletedAt: null }, select: { id: true } });
  const method = input.paymentMethodId ? await tx.paymentMethod.findFirst({ where: { id: input.paymentMethodId, companyId, active: true, deletedAt: null }, select: { id: true } }) : null;
  const term = input.paymentTermId ? await tx.paymentTerm.findFirst({ where: { id: input.paymentTermId, companyId, active: true, deletedAt: null }, select: { id: true } }) : null;
  const location = await tx.location.findFirst({ where: { id: input.locationId, companyId, active: true, deletedAt: null }, select: { id: true } });
  const document = input.documentId ? await tx.businessDocument.findFirst({ where: { id: input.documentId, companyId, locationId: input.locationId, deletedAt: null }, select: { id: true, partnerId: true, documentType: true } }) : null;
  if (!location || !partner || (input.documentId && !document) || (input.paymentMethodId && !method) || (input.paymentTermId && !term)) throw new TreasuryDomainError("Riferimenti scadenza non validi per la Company o la sede corrente.");
  if (document && (document.partnerId !== partner.id || (input.documentType && input.documentType !== document.documentType))) throw new TreasuryDomainError("Documento e scadenza non sono coerenti.");
  const row = await tx.paymentSchedule.create({ data: { companyId, locationId: input.locationId, partnerId: partner.id, documentId: input.documentId, installmentNumber, documentType: input.documentType, direction: input.direction, dueDate: input.dueDate, amount, residualAmount: amount, currency: (input.currency ?? "EUR").toUpperCase().slice(0, 3), paymentMethodId: method?.id, paymentTermId: term?.id, notes: input.notes?.trim() || null, createdById: userId, updatedById: userId }, select: { id: true } });
  await emit(tx, companyId, "PaymentScheduleCreated", "PaymentSchedule", row.id, { direction: input.direction, amount, installmentNumber, documentId: input.documentId ?? null });
  await emit(tx, companyId, "CashFlowForecastUpdated", "Company", companyId, { reason: "PaymentScheduleCreated", scheduleId: row.id });
  return row;
}

type Installment = { days: number; percentage: number };
function dueDate(base: Date, days: number, endOfMonth = false) { const date = new Date(base); date.setDate(date.getDate() + days); if (endOfMonth) date.setMonth(date.getMonth() + 1, 0); return date; }
export async function generateSchedulesForPostedDocument(tx: Tx, companyId: string, userId: string, documentId: string) {
  if (!await moduleEnabled(tx, companyId, MODULE_CODES.CORE_TREASURY)) return [];
  const document = await tx.businessDocument.findFirst({ where: { id: documentId, companyId, status: "CONFIRMED", documentType: { in: ["SALES_INVOICE", "PURCHASE_INVOICE", "CREDIT_NOTE"] }, deletedAt: null }, include: { paymentTerm: true, partner: { select: { isCustomer: true, isSupplier: true } }, targetLinks: { include: { sourceDocument: { select: { documentType: true } } } } } });
  if (!document || !document.locationId || await tx.paymentSchedule.count({ where: { companyId, locationId: document.locationId, documentId } })) return [];
  const sourceType = document.targetLinks[0]?.sourceDocument.documentType;
  const salesCredit = document.documentType === "CREDIT_NOTE" && (sourceType === "RETURN" ? document.partner.isCustomer && !document.partner.isSupplier : document.partner.isCustomer);
  const sourceModule = document.documentType === "SALES_INVOICE" || salesCredit ? MODULE_CODES.CORE_SALES : MODULE_CODES.CORE_PURCHASES;
  if (!await moduleEnabled(tx, companyId, sourceModule)) return [];
  const direction: PaymentScheduleDirection = document.documentType === "SALES_INVOICE" || salesCredit ? "RECEIVABLE" : "PAYABLE";
  const raw = document.paymentTerm?.installments;
  const installments: Installment[] = Array.isArray(raw) ? raw.filter((row): row is Installment => Boolean(row && typeof row === "object" && "days" in row && "percentage" in row)).map((row) => ({ days: Number(row.days), percentage: Number(row.percentage) })) : [{ days: document.paymentTerm?.dueDays ?? 0, percentage: 100 }];
  if (!installments.length || installments.some((row) => !Number.isInteger(row.days) || row.days < 0 || !Number.isFinite(row.percentage) || row.percentage <= 0) || Math.abs(installments.reduce((sum, row) => sum + row.percentage, 0) - 100) > 0.001) throw new TreasuryDomainError("Condizione di pagamento rateale non valida: il totale deve essere 100%.");
  const total = Number(document.total); let allocated = 0; const rows = [];
  for (let index = 0; index < installments.length; index += 1) { const installment = installments[index]; const amount = index === installments.length - 1 ? money(total - allocated) : money(total * installment.percentage / 100); allocated += amount; rows.push(await createSchedule(tx, companyId, userId, { locationId: document.locationId, partnerId: document.partnerId, documentId: document.id, documentType: document.documentType, direction, dueDate: dueDate(document.documentDate, installment.days, document.paymentTerm?.endOfMonth), amount, currency: document.currency, paymentMethodId: document.paymentMethodId, paymentTermId: document.paymentTermId }, index + 1)); }
  return rows;
}

export type FinancialMovementInput = { locationId: string; financialAccountId: string; partnerId?: string | null; scheduleId?: string | null; documentId?: string | null; amount: number; currency?: string; exchangeRate?: number; occurredAt?: Date; valueDate?: Date | null; reference?: string | null; notes?: string | null };
type MovementInput = FinancialMovementInput;
async function postMovement(tx: Tx, companyId: string, userId: string, movementType: FinancialMovementType, direction: FinancialMovementDirection, input: MovementInput) {
  const amount = positive(input.amount); const exchangeRate = positive(input.exchangeRate ?? 1, "Cambio");
  const account = await tx.financialAccount.findFirst({ where: { id: input.financialAccountId, companyId, locationId: input.locationId, active: true, deletedAt: null }, select: { id: true, locationId: true, currency: true, allowOverdraft: true } });
  if (!account) throw new TreasuryDomainError("Conto finanziario non attivo o non appartenente alla Company.");
  if (direction === "OUT" && !account.allowOverdraft && await accountBalance(tx, companyId, input.locationId, account.id) < amount) throw new TreasuryDomainError("Saldo insufficiente: lo scoperto non è consentito.");
  let partnerId: string | undefined; let scheduleId: string | undefined; let documentId: string | undefined;
  if (input.partnerId) { const partner = await tx.partner.findFirst({ where: { id: input.partnerId, companyId, active: true, deletedAt: null }, select: { id: true } }); if (!partner) throw new TreasuryDomainError("Partner non valido per la Company."); partnerId = partner.id; }
  if (input.scheduleId) { const schedule = await tx.paymentSchedule.findFirst({ where: { id: input.scheduleId, companyId, locationId: input.locationId, deletedAt: null }, select: { id: true, locationId: true, partnerId: true, documentId: true, direction: true } }); if (!schedule) throw new TreasuryDomainError("Scadenza non valida per la Company o la sede corrente."); if ((direction === "IN") !== (schedule.direction === "RECEIVABLE")) throw new TreasuryDomainError("Direzione movimento incompatibile con la scadenza."); scheduleId = schedule.id; partnerId ??= schedule.partnerId; documentId = schedule.documentId ?? undefined; }
  if (input.documentId) { const document = await tx.businessDocument.findFirst({ where: { id: input.documentId, companyId, locationId: input.locationId, deletedAt: null }, select: { id: true, locationId: true, partnerId: true } }); if (!document) throw new TreasuryDomainError("Documento non valido per la Company."); documentId = document.id; partnerId ??= document.partnerId; }
  return tx.financialMovement.create({ data: { companyId, locationId: input.locationId, financialAccountId: account.id, partnerId, paymentScheduleId: scheduleId, documentId, movementType, direction, amount, currency: (input.currency ?? account.currency).toUpperCase().slice(0, 3), exchangeRate, occurredAt: input.occurredAt ?? new Date(), valueDate: input.valueDate, reference: input.reference?.trim() || null, notes: input.notes?.trim() || null, postedById: userId }, select: { id: true, amount: true } });
}
export async function createFinancialMovementTx(tx: Tx, companyId: string, userId: string, movementType: FinancialMovementType, direction: FinancialMovementDirection, input: FinancialMovementInput) { return postMovement(tx, companyId, userId, movementType, direction, input); }
export async function registerCustomerReceiptTx(tx: Tx, companyId: string, userId: string, input: FinancialMovementInput) { const row = await postMovement(tx, companyId, userId, "CUSTOMER_RECEIPT", "IN", input); if (input.scheduleId) await allocate(tx, companyId, input.locationId, userId, row.id, input.scheduleId, Number(row.amount)); await emit(tx, companyId, "CustomerReceiptPosted", "FinancialMovement", row.id, { amount: Number(row.amount) }); return row; }
export async function registerSupplierPaymentTx(tx: Tx, companyId: string, userId: string, input: FinancialMovementInput) { const row = await postMovement(tx, companyId, userId, "SUPPLIER_PAYMENT", "OUT", input); if (input.scheduleId) await allocate(tx, companyId, input.locationId, userId, row.id, input.scheduleId, Number(row.amount)); await emit(tx, companyId, "SupplierPaymentPosted", "FinancialMovement", row.id, { amount: Number(row.amount) }); return row; }
export async function registerCustomerReceipt(companyId: string, userId: string, input: FinancialMovementInput) { return prisma.$transaction((tx) => registerCustomerReceiptTx(tx, companyId, userId, input), { isolationLevel: "Serializable" }); }
export async function registerSupplierPayment(companyId: string, userId: string, input: FinancialMovementInput) { return prisma.$transaction((tx) => registerSupplierPaymentTx(tx, companyId, userId, input), { isolationLevel: "Serializable" }); }

export async function allocateMovementToScheduleTx(tx: Tx, companyId: string, locationId: string, userId: string, movementId: string, scheduleId: string, rawAmount: number) { const amount = positive(rawAmount); const movement = await tx.financialMovement.findFirst({ where: { id: movementId, companyId, locationId }, select: { id: true, direction: true } }); const schedule = await tx.paymentSchedule.findFirst({ where: { id: scheduleId, companyId, locationId, deletedAt: null, status: { in: ["OPEN", "PARTIALLY_PAID", "OVERDUE"] } }, select: { id: true, direction: true, residualAmount: true } }); if (!movement || !schedule) throw new TreasuryDomainError("Movimento o scadenza non allocabile."); if ((schedule.direction === "RECEIVABLE" && movement.direction !== "IN") || (schedule.direction === "PAYABLE" && movement.direction !== "OUT")) throw new TreasuryDomainError("Direzione movimento incompatibile con la scadenza."); const residual = Number(schedule.residualAmount); if (amount > residual) throw new TreasuryDomainError("Allocazione superiore al residuo."); await tx.financialAllocation.create({ data: { companyId, locationId, movementId, scheduleId, amount } }); const next = money(residual - amount); await tx.paymentSchedule.update({ where: { id: schedule.id }, data: { residualAmount: next, status: next === 0 ? "PAID" : "PARTIALLY_PAID", updatedById: userId } }); }
const allocate = allocateMovementToScheduleTx;
export async function allocateMovementToSchedule(companyId: string, locationId: string, userId: string, movementId: string, scheduleId: string, amount: number) { return prisma.$transaction((tx) => allocate(tx, companyId, locationId, userId, movementId, scheduleId, amount), { isolationLevel: "Serializable" }); }
export async function unallocateMovement(companyId: string, locationId: string, userId: string, movementId: string, scheduleId: string) { return prisma.$transaction(async (tx) => { const allocation = await tx.financialAllocation.findFirst({ where: { companyId, locationId, movementId, scheduleId, reversedAt: null }, include: { schedule: { select: { residualAmount: true, amount: true, dueDate: true } } } }); if (!allocation) throw new TreasuryDomainError("Allocazione attiva non trovata."); const residual = money(Number(allocation.schedule.residualAmount) + Number(allocation.amount)); await tx.financialAllocation.update({ where: { id: allocation.id }, data: { reversedAt: new Date() } }); await tx.paymentSchedule.update({ where: { id: scheduleId }, data: { residualAmount: residual, status: residual >= Number(allocation.schedule.amount) ? (allocation.schedule.dueDate < new Date() ? "OVERDUE" : "OPEN") : "PARTIALLY_PAID", updatedById: userId } }); }); }
export async function reverseFinancialMovement(companyId: string, locationId: string, userId: string, movementId: string, notes?: string) { return prisma.$transaction(async (tx) => { const original = await tx.financialMovement.findFirst({ where: { id: movementId, companyId, locationId }, include: { reversals: { select: { id: true } }, allocations: { where: { reversedAt: null }, include: { schedule: true } } } }); if (!original || original.movementType === "REVERSAL") throw new TreasuryDomainError("Movimento non reversibile."); if (original.reversals.length) throw new TreasuryDomainError("Il movimento è già stato stornato."); for (const allocation of original.allocations) { const residual = money(Number(allocation.schedule.residualAmount) + Number(allocation.amount)); await tx.financialAllocation.update({ where: { id: allocation.id }, data: { reversedAt: new Date() } }); await tx.paymentSchedule.update({ where: { id: allocation.scheduleId }, data: { residualAmount: residual, status: residual >= Number(allocation.schedule.amount) ? (allocation.schedule.dueDate < new Date() ? "OVERDUE" : "OPEN") : "PARTIALLY_PAID", updatedById: userId } }); } const row = await tx.financialMovement.create({ data: { companyId, locationId, financialAccountId: original.financialAccountId, partnerId: original.partnerId, paymentScheduleId: original.paymentScheduleId, documentId: original.documentId, movementType: "REVERSAL", direction: original.direction === "IN" ? "OUT" : "IN", amount: original.amount, currency: original.currency, exchangeRate: original.exchangeRate, occurredAt: new Date(), reference: original.reference, notes: notes?.trim() || `Storno ${original.id}`, postedById: userId, reversalOfId: original.id }, select: { id: true } }); await emit(tx, companyId, "FinancialMovementReversed", "FinancialMovement", row.id, { reversalOfId: original.id }); return row; }, { isolationLevel: "Serializable" }); }

export async function createFinancialTransfer(companyId: string, locationId: string, userId: string, input: { sourceAccountId: string; destinationAccountId: string; amount: number; currency?: string; transferDate?: Date }) { if (input.sourceAccountId === input.destinationAccountId) throw new TreasuryDomainError("I conti del trasferimento devono essere differenti."); const amount = positive(input.amount); const accounts = await prisma.financialAccount.count({ where: { companyId, locationId, id: { in: [input.sourceAccountId, input.destinationAccountId] }, active: true, deletedAt: null } }); if (accounts !== 2) throw new TreasuryDomainError("Conti del trasferimento non validi."); return prisma.financialTransfer.create({ data: { companyId, locationId, sourceAccountId: input.sourceAccountId, destinationAccountId: input.destinationAccountId, amount, currency: input.currency ?? "EUR", transferDate: input.transferDate ?? new Date(), createdById: userId }, select: { id: true } }); }
export async function completeFinancialTransfer(companyId: string, locationId: string, userId: string, transferId: string) { return prisma.$transaction(async (tx) => { const transfer = await tx.financialTransfer.findFirst({ where: { id: transferId, companyId, locationId, status: "DRAFT" } }); if (!transfer) throw new TreasuryDomainError("Trasferimento non disponibile o già completato."); const out = await postMovement(tx, companyId, userId, "TRANSFER_OUT", "OUT", { locationId, financialAccountId: transfer.sourceAccountId, amount: Number(transfer.amount), currency: transfer.currency, occurredAt: transfer.transferDate, reference: `Transfer:${transfer.id}` }); const incoming = await postMovement(tx, companyId, userId, "TRANSFER_IN", "IN", { locationId, financialAccountId: transfer.destinationAccountId, amount: Number(transfer.amount), currency: transfer.currency, occurredAt: transfer.transferDate, reference: `Transfer:${transfer.id}` }); await tx.financialTransfer.update({ where: { id: transfer.id }, data: { status: "COMPLETED", completedById: userId, completedAt: new Date() } }); await emit(tx, companyId, "FinancialTransferCompleted", "FinancialTransfer", transfer.id, { outMovementId: out.id, inMovementId: incoming.id }); return { id: transfer.id }; }, { isolationLevel: "Serializable" }); }

async function accountBalance(tx: Tx, companyId: string, locationId: string, accountId: string) { const account = await tx.financialAccount.findFirst({ where: { id: accountId, companyId, locationId, deletedAt: null }, select: { openingBalance: true } }); if (!account) throw new TreasuryDomainError("Conto non trovato."); const grouped = await tx.financialMovement.groupBy({ by: ["direction"], where: { companyId, locationId, financialAccountId: accountId }, _sum: { amount: true } }); return money(Number(account.openingBalance) + grouped.reduce((sum, row) => sum + (row.direction === "IN" ? 1 : -1) * Number(row._sum.amount ?? 0), 0)); }
export async function getAccountBalance(companyId: string, locationId: string, accountId: string) { return prisma.$transaction((tx) => accountBalance(tx, companyId, locationId, accountId)); }
export async function getOpenReceivables(companyId: string, locationId: string) { return prisma.paymentSchedule.findMany({ where: { companyId, locationId, direction: "RECEIVABLE", status: { in: ["OPEN", "PARTIALLY_PAID", "OVERDUE", "DISPUTED"] }, deletedAt: null }, include: { partner: { select: { id: true, name: true, displayName: true } }, document: { select: { documentNumber: true } } }, orderBy: { dueDate: "asc" } }); }
export async function getOpenPayables(companyId: string, locationId: string) { return prisma.paymentSchedule.findMany({ where: { companyId, locationId, direction: "PAYABLE", status: { in: ["OPEN", "PARTIALLY_PAID", "OVERDUE", "DISPUTED"] }, deletedAt: null }, include: { partner: { select: { id: true, name: true, displayName: true } }, document: { select: { documentNumber: true } } }, orderBy: { dueDate: "asc" } }); }
export async function getOverdueSchedules(companyId: string, locationId: string, userId?: string) { const now = new Date(); if (userId) await prisma.$transaction(async (tx) => { const rows = await tx.paymentSchedule.findMany({ where: { companyId, locationId, dueDate: { lt: now }, status: "OPEN", deletedAt: null }, select: { id: true } }); for (const row of rows) { await tx.paymentSchedule.update({ where: { id: row.id }, data: { status: "OVERDUE", updatedById: userId } }); await emit(tx, companyId, "PaymentScheduleOverdue", "PaymentSchedule", row.id); } }); return prisma.paymentSchedule.findMany({ where: { companyId, locationId, dueDate: { lt: now }, status: { in: ["OPEN", "PARTIALLY_PAID", "OVERDUE"] }, deletedAt: null }, include: { partner: { select: { name: true, displayName: true } } }, orderBy: { dueDate: "asc" } }); }
export async function getCashFlowForecast(companyId: string, locationId: string, horizons = [30, 60, 90]) { const accounts = await prisma.financialAccount.findMany({ where: { companyId, locationId, active: true, deletedAt: null }, select: { id: true, code: true, name: true } }); const balances = await Promise.all(accounts.map(async (account) => ({ ...account, balance: await getAccountBalance(companyId, locationId, account.id) }))); const opening = money(balances.reduce((sum, row) => sum + row.balance, 0)); const now = new Date(); const periods = await Promise.all(horizons.map(async (days) => { const end = new Date(now); end.setDate(end.getDate() + days); const grouped = await prisma.paymentSchedule.groupBy({ by: ["direction"], where: { companyId, locationId, dueDate: { lte: end }, status: { in: ["OPEN", "PARTIALLY_PAID", "OVERDUE"] }, deletedAt: null }, _sum: { residualAmount: true } }); const incoming = Number(grouped.find((row) => row.direction === "RECEIVABLE")?._sum.residualAmount ?? 0); const outgoing = Number(grouped.find((row) => row.direction === "PAYABLE")?._sum.residualAmount ?? 0); return { days, incoming: money(incoming), outgoing: money(outgoing), projectedBalance: money(opening + incoming - outgoing) }; })); return { generatedAt: now, openingBalance: opening, accounts: balances, periods } as const; }

export async function importBankStatement(companyId: string, locationId: string, accountId: string, input: { statementDate: Date; openingBalance: number; closingBalance: number; lines: { transactionDate: Date; valueDate?: Date | null; amount: number; description: string; reference?: string | null }[] }) {
  const account = await prisma.financialAccount.findFirst({ where: { id: accountId, companyId, locationId, type: "BANK", active: true, deletedAt: null }, select: { id: true } });
  if (!account) throw new TreasuryDomainError("Conto bancario non valido.");
  return prisma.$transaction(async (tx) => {
    const row = await tx.bankStatement.create({ data: { id: randomUUID(), companyId, locationId, financialAccountId: account.id, statementDate: input.statementDate, openingBalance: input.openingBalance, closingBalance: input.closingBalance }, select: { id: true } });
    if (input.lines.length) await tx.bankStatementLine.createMany({ data: input.lines.map((line) => ({ companyId, locationId, bankStatementId: row.id, transactionDate: line.transactionDate, valueDate: line.valueDate, amount: line.amount, description: line.description, reference: line.reference })) });
    await emit(tx, companyId, "BankStatementImported", "BankStatement", row.id, { lineCount: input.lines.length });
    return row;
  });
}
async function updateStatementStatus(tx: Tx, companyId: string, locationId: string, statementId: string) { const total = await tx.bankStatementLine.count({ where: { companyId, locationId, bankStatementId: statementId } }); const matched = await tx.bankStatementLine.count({ where: { companyId, locationId, bankStatementId: statementId, reconciliationStatus: "MATCHED" } }); await tx.bankStatement.update({ where: { id: statementId }, data: { status: total > 0 && total === matched ? "RECONCILED" : matched ? "PARTIALLY_RECONCILED" : "IMPORTED" } }); }
export async function matchStatementLine(companyId: string, locationId: string, lineId: string, movementId: string) { return prisma.$transaction(async (tx) => { const line = await tx.bankStatementLine.findFirst({ where: { id: lineId, companyId, locationId, reconciliationStatus: "UNMATCHED" }, include: { bankStatement: { select: { financialAccountId: true } } } }); const movement = await tx.financialMovement.findFirst({ where: { id: movementId, companyId, locationId }, select: { id: true, financialAccountId: true, direction: true, amount: true } }); if (!line || !movement || line.bankStatement.financialAccountId !== movement.financialAccountId || money(Number(line.amount)) !== money((movement.direction === "IN" ? 1 : -1) * Number(movement.amount))) throw new TreasuryDomainError("Riga e movimento non sono riconciliabili."); await tx.bankStatementLine.update({ where: { id: line.id }, data: { matchedMovementId: movement.id, reconciliationStatus: "MATCHED" } }); await updateStatementStatus(tx, companyId, locationId, line.bankStatementId); await emit(tx, companyId, "BankStatementLineReconciled", "BankStatementLine", line.id, { movementId }); }); }
export async function unmatchStatementLine(companyId: string, locationId: string, lineId: string) { return prisma.$transaction(async (tx) => { const line = await tx.bankStatementLine.findFirst({ where: { id: lineId, companyId, locationId, reconciliationStatus: "MATCHED" } }); if (!line) throw new TreasuryDomainError("Riga riconciliata non trovata."); await tx.bankStatementLine.update({ where: { id: line.id }, data: { matchedMovementId: null, reconciliationStatus: "UNMATCHED" } }); await updateStatementStatus(tx, companyId, locationId, line.bankStatementId); }); }

export async function createFinancialAccount(companyId: string, locationId: string, userId: string, input: { code: string; name: string; type: "BANK" | "CASH" | "CARD" | "PAYPAL" | "OTHER"; currency?: string; iban?: string | null; bic?: string | null; bankName?: string | null; openingBalance?: number; allowOverdraft?: boolean }) { if (!input.code.trim() || !input.name.trim()) throw new TreasuryDomainError("Codice e nome sono obbligatori."); return prisma.financialAccount.create({ data: { companyId, locationId, code: input.code.trim().toUpperCase(), name: input.name.trim(), type: input.type, currency: input.currency ?? "EUR", iban: input.iban?.trim() || null, bic: input.bic?.trim() || null, bankName: input.bankName?.trim() || null, openingBalance: input.openingBalance ?? 0, allowOverdraft: Boolean(input.allowOverdraft), createdById: userId, updatedById: userId }, select: { id: true } }); }
export async function updateFinancialAccount(companyId: string, locationId: string, userId: string, accountId: string, input: { code: string; name: string; type: "BANK" | "CASH" | "CARD" | "PAYPAL" | "OTHER"; currency: string; iban?: string | null; bic?: string | null; bankName?: string | null; active: boolean }) { const code = input.code.trim().toUpperCase(); const name = input.name.trim(); const currency = input.currency.trim().toUpperCase().slice(0, 3); if (!code || !name || currency.length !== 3) throw new TreasuryDomainError("Codice, nome e valuta sono obbligatori."); return prisma.$transaction(async (tx) => { const account = await tx.financialAccount.findFirst({ where: { id: accountId, companyId, locationId, deletedAt: null }, select: { id: true } }); if (!account) throw new TreasuryDomainError("Conto finanziario non trovato nella Company attiva."); if (await tx.financialAccount.count({ where: { companyId, code, id: { not: account.id } } })) throw new TreasuryDomainError("Il codice conto è già utilizzato nella Company."); await tx.financialAccount.update({ where: { id: account.id }, data: { code, name, type: input.type, currency, iban: input.iban?.trim() || null, bic: input.bic?.trim() || null, bankName: input.bankName?.trim() || null, active: input.active, updatedById: userId } }); return { id: account.id }; }); }
export async function getTreasuryAccounts(companyId: string, locationId: string) { const rows = await prisma.financialAccount.findMany({ where: { companyId, locationId, deletedAt: null }, select: { id: true, code: true, name: true, type: true, currency: true, active: true, openingBalance: true }, orderBy: { code: "asc" } }); return Promise.all(rows.map(async (row) => ({ ...row, balance: await getAccountBalance(companyId, locationId, row.id) }))); }
export async function getTreasuryAccount(companyId: string, locationId: string, id: string) { const row = await prisma.financialAccount.findFirst({ where: { id, companyId, locationId, deletedAt: null }, include: { movements: { where: { locationId }, orderBy: { occurredAt: "desc" }, take: 30 } } }); return row ? { ...row, balance: await getAccountBalance(companyId, locationId, id) } : null; }
export async function getFinancialMovements(companyId: string, locationId: string) { return prisma.financialMovement.findMany({ where: { companyId, locationId }, include: { financialAccount: { select: { code: true, name: true } }, partner: { select: { name: true, displayName: true } }, allocations: { where: { reversedAt: null }, include: { schedule: { select: { dueDate: true } } } }, reversalOf: { select: { id: true } }, reversals: { select: { id: true } } }, orderBy: [{ occurredAt: "desc" }, { createdAt: "desc" }], take: 100 }); }
export async function getFinancialMovement(companyId: string, locationId: string, id: string) { return prisma.financialMovement.findFirst({ where: { id, companyId, locationId }, include: { financialAccount: true, partner: true, paymentSchedule: true, allocations: { include: { schedule: true } }, reversalOf: true, reversals: true } }); }
export async function getFinancialTransfers(companyId: string, locationId: string) { return prisma.financialTransfer.findMany({ where: { companyId, locationId }, include: { sourceAccount: { select: { code: true, name: true } }, destinationAccount: { select: { code: true, name: true } } }, orderBy: { transferDate: "desc" } }); }
export async function getFinancialTransfer(companyId: string, locationId: string, id: string) { return prisma.financialTransfer.findFirst({ where: { id, companyId, locationId }, include: { sourceAccount: true, destinationAccount: true } }); }
export async function getBankStatements(companyId: string, locationId: string) { return prisma.bankStatement.findMany({ where: { companyId, locationId }, include: { financialAccount: { select: { code: true, name: true } }, _count: { select: { lines: true } } }, orderBy: { statementDate: "desc" } }); }
export async function getBankStatement(companyId: string, locationId: string, id: string) { return prisma.bankStatement.findFirst({ where: { id, companyId, locationId }, include: { financialAccount: true, lines: { include: { matchedMovement: true }, orderBy: { transactionDate: "asc" } } } }); }
export async function addBankStatementLine(companyId: string, locationId: string, statementId: string, input: { transactionDate: Date; valueDate?: Date | null; amount: number; description: string; reference?: string | null }) { const amount = Number(input.amount); const description = input.description.trim(); if (!Number.isFinite(amount) || amount === 0 || !description) throw new TreasuryDomainError("Importo diverso da zero e descrizione sono obbligatori."); return prisma.$transaction(async (tx) => { const statement = await tx.bankStatement.findFirst({ where: { id: statementId, companyId, locationId, status: { in: ["IMPORTED", "PARTIALLY_RECONCILED"] } }, select: { id: true, openingBalance: true } }); if (!statement) throw new TreasuryDomainError("Estratto conto non modificabile o non appartenente alla Company."); const row = await tx.bankStatementLine.create({ data: { companyId, locationId, bankStatementId: statement.id, transactionDate: input.transactionDate, valueDate: input.valueDate, amount, description, reference: input.reference?.trim() || null }, select: { id: true } }); const total = await tx.bankStatementLine.aggregate({ where: { companyId, locationId, bankStatementId: statement.id }, _sum: { amount: true } }); await tx.bankStatement.update({ where: { id: statement.id }, data: { closingBalance: money(Number(statement.openingBalance) + Number(total._sum.amount ?? 0)) } }); return row; }); }
export async function getTreasuryOptions(companyId: string, locationId: string) { const [accounts, partners, schedules, movements, paymentMethods, paymentTerms] = await Promise.all([prisma.financialAccount.findMany({ where: { companyId, locationId, active: true, deletedAt: null }, select: { id: true, code: true, name: true, type: true }, orderBy: { code: "asc" } }), prisma.partner.findMany({ where: { companyId, active: true, deletedAt: null }, select: { id: true, name: true, displayName: true, isCustomer: true, isSupplier: true }, orderBy: { name: "asc" } }), prisma.paymentSchedule.findMany({ where: { companyId, locationId, status: { in: ["OPEN", "PARTIALLY_PAID", "OVERDUE"] }, deletedAt: null }, select: { id: true, direction: true, dueDate: true, residualAmount: true, partner: { select: { name: true } } }, orderBy: { dueDate: "asc" } }), prisma.financialMovement.findMany({ where: { companyId, locationId, matchedStatementLines: { none: {} } }, select: { id: true, direction: true, amount: true, occurredAt: true, reference: true, financialAccountId: true }, orderBy: { occurredAt: "desc" }, take: 100 }), prisma.paymentMethod.findMany({ where: { companyId, active: true, deletedAt: null }, select: { id: true, code: true, name: true }, orderBy: { name: "asc" } }), prisma.paymentTerm.findMany({ where: { companyId, active: true, deletedAt: null }, select: { id: true, code: true, name: true }, orderBy: { name: "asc" } })]); return { accounts, partners, schedules, movements, paymentMethods, paymentTerms }; }
export async function getTreasuryDashboard(companyId: string, locationId: string) { const [accounts, receivables, payables, overdue, forecast, movements] = await Promise.all([getTreasuryAccounts(companyId, locationId), getOpenReceivables(companyId, locationId), getOpenPayables(companyId, locationId), getOverdueSchedules(companyId, locationId), getCashFlowForecast(companyId, locationId), getFinancialMovements(companyId, locationId)]); const month = new Date(); month.setDate(1); month.setHours(0, 0, 0, 0); const totals = await prisma.financialMovement.groupBy({ by: ["movementType"], where: { companyId, locationId, occurredAt: { gte: month }, movementType: { in: ["CUSTOMER_RECEIPT", "SUPPLIER_PAYMENT"] } }, _sum: { amount: true } }); return { accounts, receivables: money(receivables.reduce((s, r) => s + Number(r.residualAmount), 0)), payables: money(payables.reduce((s, r) => s + Number(r.residualAmount), 0)), overdue: money(overdue.reduce((s, r) => s + Number(r.residualAmount), 0)), forecast, movements: movements.slice(0, 10), receiptsMonth: Number(totals.find((r) => r.movementType === "CUSTOMER_RECEIPT")?._sum.amount ?? 0), paymentsMonth: Number(totals.find((r) => r.movementType === "SUPPLIER_PAYMENT")?._sum.amount ?? 0) }; }
