import { randomUUID } from "node:crypto";
import { notFound } from "next/navigation";
import { MODULE_CODES } from "@/lib/module-catalog";
import { getRestaurantOptions } from "@/lib/restaurant";
import { requireRestaurantContext } from "@/lib/restaurant-access";
import { getOrder } from "@/lib/restaurant-orders";
import { orderAction } from "../../actions";

export default async function Page({ params }: { params: Promise<{ id: string }> }) {
  const { companyId, locationId } = await requireRestaurantContext(MODULE_CODES.RESTAURANT_FLOOR);
  const { id } = await params;
  const [order, options] = await Promise.all([getOrder(companyId, locationId, id), getRestaurantOptions(companyId, locationId)]);
  if (!order) notFound();
  const total = order.lines.filter((line) => line.status !== "CANCELLED").reduce((sum, line) => sum + Number(line.quantity) * Number(line.unitPrice) + line.modifiers.reduce((modifierSum, modifier) => modifierSum + Number(modifier.priceDelta), 0), 0);
  return <div className="space-y-4"><h1 className="text-2xl font-bold">Comanda {order.code}</h1><p>{order.status} · {order.paymentStatus} · totale {total.toFixed(2)} €</p>{order.lines.map((line) => <div className="flex min-h-11 justify-between border-b p-3" key={line.id}><span>{line.item.name} × {Number(line.quantity)} · {line.status} {line.kitchenNotes && `· ${line.kitchenNotes}`}</span>{line.status === "NEW" && <form action={orderAction}><input type="hidden" name="orderId" value={order.id}/><input type="hidden" name="lineId" value={line.id}/><button className="min-h-11 rounded border px-4" name="operation" value="cancel">Annulla</button></form>}</div>)}{order.status !== "CLOSED" && <><form action={orderAction} className="grid gap-3 rounded border p-4 md:grid-cols-4"><input type="hidden" name="orderId" value={order.id}/><input type="hidden" name="operation" value="add"/><select name="itemId">{options.items.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><input name="quantity" type="number" min="0.001" step="0.001" defaultValue="1"/><input name="courseNumber" type="number" min="1" placeholder="Portata"/><input name="kitchenNotes" placeholder="Note cucina"/><button className="min-h-11 rounded border p-2">Aggiungi riga</button></form><form action={orderAction}><input type="hidden" name="orderId" value={order.id}/><button className="min-h-11 rounded bg-amber-600 px-5 text-white" name="operation" value="send">Invia in cucina</button></form><form action={orderAction} className="grid gap-3 rounded border p-4 md:grid-cols-4"><input type="hidden" name="orderId" value={order.id}/><input type="hidden" name="idempotencyKey" value={randomUUID()}/><select name="seriesId">{options.series.map((series) => <option value={series.id} key={series.id}>{series.code}</option>)}</select><select name="financialAccountId">{options.accounts.map((account) => <option value={account.id} key={account.id}>{account.name}</option>)}</select><select name="paymentMethod">{["CASH", "CARD", "BANK", "OTHER"].map((value) => <option key={value}>{value}</option>)}</select><input name="amount" type="number" min="0" step="0.01" defaultValue={total}/><label><input name="invoice" type="checkbox"/> Fattura</label><button className="min-h-11 rounded bg-slate-900 p-2 text-white" name="operation" value="close">Registra conto</button></form></>}</div>;
}
