"use client";

import { useMemo, useRef, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { addFloorItemAction, changeFloorGuestCountAction, changeFloorLineQuantityAction, deleteFloorLineAction, dispatchFloorOrderAction, type FloorActionResult, openFloorTableAction, retryFloorJobAction, saveFloorLineNoteAction } from "./operational-actions";

type LineState = "PENDING" | "SENDING" | "SENT" | "ERROR" | "UNCERTAIN";
type OrderLine = { id: string; itemId: string; name: string; quantity: number; sentQuantity: number; unitPrice: number; lineTotal: number; kitchenNotes: string | null; state: LineState; retryJobId: string | null };
type Order = { id: string; code: string; guestCount: number; tableIds: string[]; total: number; unsentCount: number; lines: OrderLine[] };
type Product = { id: string; name: string; plu: number; price: number | null };
type Props = { data: { areas: Array<{ id: string; name: string; tables: Array<{ id: string; code: string; name: string; seats: number; status: string }> }>; orders: Order[]; menu: { id: string | null; sections: Array<{ id: string; name: string; products: Product[] }> } } };
const money = new Intl.NumberFormat("it-IT", { style: "currency", currency: "EUR" });
const labels: Record<LineState, string> = { PENDING: "DA INVIARE", SENDING: "IN INVIO", SENT: "INVIATO", ERROR: "ERRORE", UNCERTAIN: "INVIO INCERTO" };

export function OperationalFloor({ data }: Props) {
  const router = useRouter(), [pending, startTransition] = useTransition();
  const [selectedOrderId, setSelectedOrderId] = useState<string | null>(null), [openingTableId, setOpeningTableId] = useState<string | null>(null), [guestCount, setGuestCount] = useState(2), [selectedSectionId, setSelectedSectionId] = useState(data.menu.sections[0]?.id ?? ""), [query, setQuery] = useState(""), [feedback, setFeedback] = useState<FloorActionResult | null>(null);
  const dispatchKeys = useRef(new Map<string, string>());
  const order = data.orders.find((row) => row.id === selectedOrderId) ?? null;
  const selectedSection = data.menu.sections.find((row) => row.id === selectedSectionId);
  const normalized = query.trim().toLocaleLowerCase("it-IT");
  const products = useMemo(() => {
    const sections = normalized ? data.menu.sections : selectedSection ? [selectedSection] : [];
    return sections.flatMap((section) => section.products.filter((product) => !normalized || product.name.toLocaleLowerCase("it-IT").includes(normalized) || String(product.plu).includes(normalized)).map((product) => ({ ...product, sectionName: section.name })));
  }, [data.menu.sections, normalized, selectedSection]);
  const execute = (action: () => Promise<FloorActionResult>, onSuccess?: (result: FloorActionResult) => void) => startTransition(async () => {
    setFeedback(null);
    const result = await action();
    setFeedback(result);
    if (result.ok) { onSuccess?.(result); router.refresh(); }
  });
  const open = (tableId: string) => execute(() => openFloorTableAction(tableId, guestCount), (result) => { setOpeningTableId(null); if (result.orderId) setSelectedOrderId(result.orderId); });
  const dispatch = () => {
    if (!order) return;
    const key = dispatchKeys.current.get(order.id) ?? crypto.randomUUID();
    dispatchKeys.current.set(order.id, key);
    execute(() => dispatchFloorOrderAction(order.id, key), (result) => { if (result.ok) dispatchKeys.current.delete(order.id); });
  };
  return <div className="space-y-5">
    <header><p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">Ristorante</p><h1 className="text-3xl font-bold text-slate-950">Sala</h1><p className="text-sm text-slate-600">Tavoli e comande operative · nessuna funzione di pagamento</p></header>
    {feedback && <p role="status" aria-live="polite" className={`rounded-xl p-3 text-sm ${feedback.ok ? "bg-emerald-50 text-emerald-800" : "bg-red-50 text-red-800"}`}>{feedback.message}</p>}
    {!order && <div className="space-y-6">{data.areas.map((area) => <section key={area.id}><h2 className="mb-3 text-lg font-bold">{area.name}</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{area.tables.map((table) => {
      const active = data.orders.find((candidate) => candidate.tableIds.includes(table.id));
      const available = !active && table.status === "AVAILABLE";
      const uncertain = active?.lines.some((line) => line.state === "UNCERTAIN"), failed = active?.lines.some((line) => line.state === "ERROR"), sending = active?.lines.some((line) => line.state === "SENDING");
      const state = available ? "LIBERO" : !active ? table.status.replaceAll("_", " ") : uncertain || failed ? "ERRORE CUCINA" : active.unsentCount ? "DA INVIARE" : sending ? "IN INVIO" : active.lines.length ? "INVIATO" : "APERTO";
      return <article key={table.id} className={`min-h-44 rounded-2xl border-2 p-4 shadow-sm ${available ? "border-emerald-300 bg-emerald-50" : !active ? "border-slate-300 bg-slate-100" : uncertain || failed ? "border-red-400 bg-red-50" : active.unsentCount ? "border-amber-400 bg-amber-50" : "border-blue-300 bg-blue-50"}`}><button disabled={!active && !available} className="flex h-full w-full flex-col text-left disabled:cursor-not-allowed" onClick={() => active ? setSelectedOrderId(active.id) : setOpeningTableId(table.id)}><span className="text-lg font-black">{table.name || table.code}</span><span className="mt-1 text-xs font-bold tracking-wide">{state}</span>{active && <span className="mt-auto space-y-1 text-sm"><span className="block">{active.guestCount} coperti</span><span className="block font-bold">{money.format(active.total)}</span><span className="block">{active.unsentCount} righe da inviare</span></span>}</button>{openingTableId === table.id && <div className="mt-3 flex items-center gap-2 border-t border-emerald-200 pt-3"><label className="text-sm font-semibold">Coperti <input aria-label="Numero coperti" className="ml-1 w-16 rounded border p-2" type="number" min="1" value={guestCount} onChange={(event) => setGuestCount(Number(event.target.value))}/></label><button disabled={pending || guestCount < 1} onClick={() => open(table.id)} className="min-h-11 flex-1 rounded-lg bg-slate-950 px-3 text-sm font-bold text-white disabled:opacity-50">Apri tavolo</button></div>}</article>;
    })}</div></section>)}</div>}
    {order && <><button onClick={() => setSelectedOrderId(null)} className="min-h-11 rounded-lg border px-4 text-sm font-semibold">← Tutti i tavoli</button><div className="grid gap-4 xl:grid-cols-[15rem_minmax(0,1fr)_24rem]">
      <aside className="rounded-2xl border bg-white p-3"><p className="px-2 pb-2 text-xs font-bold uppercase text-slate-500">Categorie</p><div className="flex gap-2 overflow-x-auto xl:block xl:space-y-1">{data.menu.sections.map((section) => <button key={section.id} onClick={() => { setSelectedSectionId(section.id); setQuery(""); }} className={`min-h-12 min-w-48 rounded-xl px-3 text-left text-sm font-semibold xl:w-full ${selectedSectionId === section.id && !query ? "bg-slate-950 text-white" : "bg-slate-100"}`}>{section.name}<span className="block text-xs opacity-70">{section.products.length} prodotti</span></button>)}</div></aside>
      <main className="min-w-0 rounded-2xl border bg-white p-4"><label className="sr-only" htmlFor="floor-product-search">Cerca prodotto per nome o PLU</label><input id="floor-product-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cerca nome o PLU…" className="mb-4 min-h-12 w-full rounded-xl border px-4"/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{products.map((product) => <button key={`${product.sectionName}:${product.id}`} disabled={pending} onClick={() => execute(() => addFloorItemAction(order.id, product.id))} className="min-h-28 rounded-2xl border-2 border-slate-200 bg-white p-4 text-left shadow-sm active:scale-[0.98] disabled:opacity-50"><span className="block font-bold text-slate-950">{product.name}</span><span className="mt-2 block text-lg font-black">{product.price === null ? "—" : money.format(product.price)}</span><span className="mt-1 block text-xs text-slate-500">PLU {product.plu} · {product.sectionName}</span></button>)}</div>{!products.length && <p className="py-12 text-center text-sm text-slate-500">Nessun prodotto disponibile.</p>}</main>
      <aside className="self-start rounded-2xl border bg-white p-4 xl:sticky xl:top-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase text-slate-500">Comanda corrente</p><h2 className="text-xl font-black">{order.code}</h2></div><label className="text-xs font-semibold">Coperti<input aria-label="Coperti comanda" className="mt-1 block w-16 rounded border p-2" type="number" min="1" defaultValue={order.guestCount} onBlur={(event) => { const value = Number(event.target.value); if (value !== order.guestCount) execute(() => changeFloorGuestCountAction(order.id, value)); }}/></label></div>
        <div className="mt-4 space-y-3">{order.lines.map((line) => { const editable = line.state === "PENDING" && line.sentQuantity === 0; return <article key={line.id} className="rounded-xl border p-3"><div className="flex justify-between gap-2"><div><span className={`text-xs font-black ${line.state === "UNCERTAIN" || line.state === "ERROR" ? "text-red-700" : line.state === "PENDING" ? "text-amber-700" : "text-blue-700"}`}>{labels[line.state]}</span><p className="font-semibold">{line.quantity} × {line.name}</p></div><b>{money.format(line.lineTotal)}</b></div>{line.kitchenNotes && <p className="mt-2 text-sm text-slate-600">Nota: {line.kitchenNotes}</p>}{editable && <div className="mt-3 space-y-2"><div className="flex gap-2"><button aria-label={`Riduci ${line.name}`} disabled={pending || line.quantity <= 1} onClick={() => execute(() => changeFloorLineQuantityAction(order.id, line.id, line.quantity - 1))} className="min-h-11 min-w-11 rounded border text-lg">−</button><button aria-label={`Aumenta ${line.name}`} disabled={pending} onClick={() => execute(() => changeFloorLineQuantityAction(order.id, line.id, line.quantity + 1))} className="min-h-11 min-w-11 rounded border text-lg">+</button><button disabled={pending} onClick={() => execute(() => deleteFloorLineAction(order.id, line.id))} className="min-h-11 rounded border border-red-200 px-3 text-sm text-red-700">Elimina</button></div><input aria-label={`Nota cucina ${line.name}`} defaultValue={line.kitchenNotes ?? ""} onBlur={(event) => execute(() => saveFloorLineNoteAction(order.id, line.id, event.target.value))} placeholder="Nota cucina" className="min-h-11 w-full rounded border px-3 text-sm"/></div>}{line.state === "ERROR" && line.retryJobId && <button disabled={pending} onClick={() => execute(() => retryFloorJobAction(line.retryJobId!))} className="mt-3 min-h-11 rounded border px-3 text-sm font-semibold">Riprova invio sicuro</button>}{line.state === "UNCERTAIN" && <p role="alert" className="mt-3 rounded-lg bg-red-100 p-2 text-sm font-semibold text-red-900">Invio incerto — verificare la comanda in cucina. Non reinviare automaticamente.</p>}</article>; })}{!order.lines.length && <p className="py-6 text-center text-sm text-slate-500">Comanda vuota</p>}</div>
        <div className="mt-4 border-t pt-4"><div className="flex justify-between text-lg font-black"><span>Totale</span><span>{money.format(order.total)}</span></div><button disabled={pending || order.unsentCount === 0} onClick={dispatch} className="mt-4 min-h-14 w-full rounded-xl bg-amber-600 px-4 font-black text-white disabled:bg-slate-300">{pending ? "INVIO…" : "INVIA IN CUCINA"}</button><p className="mt-2 text-xs text-slate-500">Invia esclusivamente le righe contrassegnate “DA INVIARE”. Le note restano nel ticket Nexus; FUSION XML1745 V1 non supporta note o modificatori.</p></div>
      </aside>
    </div></>}
  </div>;
}
