"use server";
import { revalidatePath } from "next/cache";import { redirect } from "next/navigation";
import { requireRestaurantContext } from "@/lib/restaurant-access";import { MODULE_CODES } from "@/lib/module-catalog";
import { saveArea,saveTable } from "@/lib/restaurant";import { createReservation,transitionReservation } from "@/lib/restaurant-reservations";import { openOrder,addOrderLine,cancelNewLine,transferOrderTable,closeOrder } from "@/lib/restaurant-orders";import { sendOrderToKitchen,advanceKitchenLine } from "@/lib/restaurant-kitchen";import { prisma } from "@/lib/prisma";
const t=(f:FormData,k:string)=>String(f.get(k)??"").trim();const n=(f:FormData,k:string)=>Number(t(f,k).replace(",","."));const done=(path:string)=>{revalidatePath("/restaurant");redirect(path)};const fail=(path:string,e:unknown)=>redirect(`${path}?error=${encodeURIComponent(e instanceof Error?e.message:"Operazione non riuscita")}`);
export async function saveAreaAction(f:FormData){const c=await requireRestaurantContext(MODULE_CODES.RESTAURANT_FLOOR,"manage");try{await saveArea(c.companyId,c.locationId,c.userId,{code:t(f,"code"),name:t(f,"name"),description:t(f,"description")})}catch(e){fail("/restaurant/areas",e)}done("/restaurant/areas?success=Area salvata")}
export async function saveTableAction(f:FormData){const c=await requireRestaurantContext(MODULE_CODES.RESTAURANT_FLOOR,"manage");try{await saveTable(c.companyId,c.locationId,{areaId:t(f,"areaId"),code:t(f,"code"),name:t(f,"name"),seats:n(f,"seats"),status:t(f,"status") as never})}catch(e){fail("/restaurant/tables",e)}done("/restaurant/tables?success=Tavolo salvato")}
export async function createReservationAction(f:FormData){const c=await requireRestaurantContext(MODULE_CODES.RESTAURANT_RESERVATIONS,"operate");let id="";try{id=(await createReservation(c.companyId,c.locationId,c.userId,{partnerId:t(f,"partnerId")||null,guestName:t(f,"guestName"),phone:t(f,"phone"),email:t(f,"email"),startTime:new Date(t(f,"startTime")),partySize:n(f,"partySize"),source:t(f,"source") as never,status:t(f,"status") as never,notes:t(f,"notes"),tableIds:f.getAll("tableIds").map(String),adminOverride:f.get("adminOverride")==="on"&&c.roles.some(r=>["ADMIN","SUPER_ADMIN"].includes(r))})).id}catch(e){fail("/restaurant/reservations/new",e)}done(`/restaurant/reservations/${id}`)}
export async function reservationStatusAction(f:FormData){const c=await requireRestaurantContext(MODULE_CODES.RESTAURANT_RESERVATIONS,"operate");const id=t(f,"id");try{await transitionReservation(c.companyId,c.locationId,c.userId,id,t(f,"status") as never)}catch(e){fail(`/restaurant/reservations/${id}`,e)}done(`/restaurant/reservations/${id}`)}
export async function createMenuAction(f:FormData){const c=await requireRestaurantContext(MODULE_CODES.RESTAURANT_MENU,"manage");const row=await prisma.restaurantMenu.create({data:{companyId:c.companyId,locationId:c.locationId,code:t(f,"code").toUpperCase(),name:t(f,"name"),description:t(f,"description")||null}});done(`/restaurant/menus/${row.id}`)}
export async function addMenuSectionAction(f:FormData){const c=await requireRestaurantContext(MODULE_CODES.RESTAURANT_MENU,"manage");const menuId=t(f,"menuId");const menu=await prisma.restaurantMenu.findFirst({where:{id:menuId,companyId:c.companyId,locationId:c.locationId,deletedAt:null}});if(!menu)fail("/restaurant/menus",new Error("Menu non valido"));await prisma.restaurantMenuSection.create({data:{companyId:c.companyId,menuId,name:t(f,"name"),sortOrder:n(f,"sortOrder")}});done(`/restaurant/menus/${menuId}`)}
export async function addMenuItemAction(f:FormData){const c=await requireRestaurantContext(MODULE_CODES.RESTAURANT_MENU,"manage");const sectionId=t(f,"sectionId"),menuId=t(f,"menuId"),itemId=t(f,"itemId");const [section,item]=await Promise.all([prisma.restaurantMenuSection.findFirst({where:{id:sectionId,companyId:c.companyId}}),prisma.item.findFirst({where:{id:itemId,companyId:c.companyId,active:true,deletedAt:null,sellable:true,type:{in:["RECIPE","PRODUCT","SERVICE"]}}})]);if(!section||!item)fail(`/restaurant/menus/${menuId}`,new Error("Sezione o Item non valido"));await prisma.restaurantMenuItem.create({data:{companyId:c.companyId,menuSectionId:sectionId,itemId,priceOverride:t(f,"priceOverride")?n(f,"priceOverride"):null}});done(`/restaurant/menus/${menuId}`)}
export async function openOrderAction(f:FormData){const c=await requireRestaurantContext(MODULE_CODES.RESTAURANT_FLOOR,"operate");let id="";try{id=(await openOrder(c.companyId,c.locationId,c.userId,{tableId:t(f,"tableId")||null,partnerId:t(f,"partnerId")||null,guestCount:n(f,"guestCount"),serviceType:t(f,"serviceType") as never,notes:t(f,"notes")})).id}catch(e){fail("/restaurant/orders/new",e)}done(`/restaurant/orders/${id}`)}
export async function orderAction(f:FormData){const c=await requireRestaurantContext(MODULE_CODES.RESTAURANT_FLOOR,"operate");const id=t(f,"orderId");try{const op=t(f,"operation");if(op==="add")await addOrderLine(c.companyId,c.locationId,id,{itemId:t(f,"itemId"),quantity:n(f,"quantity"),courseNumber:n(f,"courseNumber")||undefined,kitchenNotes:t(f,"kitchenNotes")});else if(op==="cancel")await cancelNewLine(c.companyId,c.locationId,t(f,"lineId"));else if(op==="transfer")await transferOrderTable(c.companyId,c.locationId,id,t(f,"tableId"));else if(op==="send")await sendOrderToKitchen(c.companyId,c.locationId,id);else if(op==="close")await closeOrder(c.companyId,c.locationId,c.userId,id,t(f,"idempotencyKey"),{seriesId:t(f,"seriesId"),financialAccountId:t(f,"financialAccountId"),paymentMethod:t(f,"paymentMethod") as never,amount:n(f,"amount"),invoice:f.get("invoice")==="on"})}catch(e){fail(`/restaurant/orders/${id}`,e)}done(`/restaurant/orders/${id}`)}
export async function kitchenAction(f:FormData){const c=await requireRestaurantContext(MODULE_CODES.RESTAURANT_KITCHEN,"kitchen");try{await advanceKitchenLine(c.companyId,c.locationId,c.userId,t(f,"lineId"),t(f,"status") as never)}catch(e){fail("/restaurant/kitchen",e)}done("/restaurant/kitchen")}
