import { canManageLocations, requireLocationReader } from "@/lib/location-access";
import { getLocations } from "@/lib/locations";
import Link from "next/link";

export default async function LocationsPage({ searchParams }: { searchParams: Promise<{ q?: string; lifecycle?: "current" | "archived" | "all"; success?: string }> }) {
  const context = await requireLocationReader();
  const writable = canManageLocations(context.roles);
  const params = await searchParams;
  const locations = await getLocations(context.companyId, { q: params.q, lifecycle: params.lifecycle });
  return <div className="space-y-6"><div className="flex items-start justify-between gap-4"><div><h1 className="text-3xl font-bold">Sedi</h1><p className="text-slate-500">Anagrafica delle unità operative di Company.</p></div>{writable && <Link href="/settings/locations/new" className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white">Nuova sede</Link>}</div>{params.success && <p className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{params.success}</p>}<form className="flex flex-wrap gap-3 rounded-xl border bg-white p-4"><input name="q" defaultValue={params.q} placeholder="Cerca codice, nome o città" className="rounded-lg border px-3 py-2 text-sm"/><select name="lifecycle" defaultValue={params.lifecycle ?? "current"} className="rounded-lg border px-3 py-2 text-sm"><option value="current">Correnti</option><option value="archived">Archiviate</option><option value="all">Tutte</option></select><button className="rounded-lg border px-4 py-2 text-sm">Applica</button></form><div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-sm"><thead><tr className="border-b bg-slate-50 text-left"><th className="p-4">Codice</th><th className="p-4">Sede</th><th className="p-4">Località</th><th className="p-4">Stato</th><th className="p-4"></th></tr></thead><tbody>{locations.map((location) => <tr key={location.id} className="border-b last:border-0"><td className="p-4 font-mono">{location.code}</td><td className="p-4"><span className="font-medium">{location.name}</span>{location.isHeadquarters && <span className="ml-2 rounded bg-slate-900 px-2 py-1 text-xs text-white">Headquarters</span>}</td><td className="p-4">{[location.city, location.province].filter(Boolean).join(", ") || "—"}</td><td className="p-4">{location.deletedAt ? "Archiviata" : location.active ? "Attiva" : "Non attiva"}</td><td className="p-4 text-right"><Link href={`/settings/locations/${location.id}`} className="underline">Dettaglio</Link></td></tr>)}</tbody></table></div></div>;
}
