import Link from "next/link";
import { requireRestaurantContext } from "@/lib/restaurant-access";
import { MODULE_CODES } from "@/lib/module-catalog";
import { getKitchen } from "@/lib/restaurant-kitchen";
import { prisma } from "@/lib/prisma";
import { kitchenAction } from "../actions";
import ElapsedSince from "./elapsed";
export default async function Page({searchParams}:{searchParams:Promise<{station?:string;status?:string;table?:string}>}) {
 const c=await requireRestaurantContext(MODULE_CODES.RESTAURANT_KITCHEN,"kitchen"),q=await searchParams;
 const [rows,stations]=await Promise.all([getKitchen(c.companyId,c.locationId,{stationId:q.station,status:q.status as never,table:q.table}),prisma.kitchenStation.findMany({where:{companyId:c.companyId,locationId:c.locationId,active:true},orderBy:{sortOrder:"asc"}})]);
 return <div className="space-y-4"><div className="flex flex-wrap justify-between gap-2"><h1 className="text-2xl font-bold">Kitchen display</h1><div className="flex gap-2"><Link className="rounded border p-2" href="/restaurant/kitchen/print-queue">Coda stampa</Link><Link className="rounded border p-2" href="/restaurant/settings/kitchen">Impostazioni</Link></div></div><form className="grid gap-2 rounded border p-3 md:grid-cols-4"><select name="station" defaultValue={q.station}><option value="">Tutte le postazioni</option>{stations.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select name="status" defaultValue={q.status}><option value="">Stati attivi</option>{["NEW","IN_PREPARATION","READY","COMPLETED","CANCELLED"].map(s=><option key={s}>{s}</option>)}</select><input name="table" defaultValue={q.table} placeholder="Tavolo"/><button className="rounded border p-2">Filtra</button></form>{rows.map(t=><section className="rounded border p-4" data-order-id={t.orderId} data-ticket-id={t.id} key={t.id}><div className="flex justify-between"><b>{t.stationName} · {t.orderCode} · invio #{t.dispatchNumber}</b><span>{t.dispatchType}</span></div><p>{Array.isArray(t.tableNames)?t.tableNames.join(", "):""} · {t.guestCount} coperti</p><ElapsedSince since={t.createdAt}/>{t.lines.map(l=><div className="flex items-center justify-between border-t py-2" key={l.id}><span><b>{Number(l.quantity)} × {l.productName}</b> · {l.status}{l.variantName&&<small className="block">Variante: {l.variantName}</small>}{Array.isArray(l.modifiers)&&l.modifiers.map((m,index)=><small className="block" key={index}>+ {String((m as {name?:string}).name??m)}</small>)}{l.notes&&<small className="block">NOTA: {l.notes}</small>}{Array.isArray(l.allergens)&&l.allergens.length>0&&<small className="block font-bold text-red-700">ALLERGENI: {l.allergens.map(a=>String((a as {name?:string}).name??a)).join(", ")}</small>}</span>{t.dispatchType!=="CANCELLATION"&&<form action={kitchenAction}><input type="hidden" name="lineId" value={l.orderLineId}/>{["IN_PREPARATION","READY","SERVED"].map(s=><button className="ml-2 rounded border p-1" name="status" value={s} key={s}>{s}</button>)}</form>}</div>)}</section>)}</div>;
}
