"use client";
import { useActionState } from "react";
import { KeyRound, Printer, RefreshCw, Unplug } from "lucide-react";
import { connectorAdminAction, type ConnectorActionState } from "./connector-actions";
type Device = { id:string;name:string;status:string;online:boolean;printerOnline:boolean;credentialPrefix:string;lastHeartbeatAt:string|null;lastError:string|null;diagnostics:unknown;printer:{name:string;station:{name:string}} };
type CatalogState={status:string;lastSyncAt:string|null;totalCount:number;createdCount:number;updatedCount:number;unchangedCount:number;missingCount:number;errorCount:number;lastError:string|null};
export function ConnectorPanel({devices,printers,catalog}:{devices:Device[];printers:{id:string;name:string}[];catalog:CatalogState[]}) {
 const [state,action,pending]=useActionState<ConnectorActionState,FormData>(connectorAdminAction,{});
 return <section className="space-y-3 border-t pt-5"><div><h2 className="text-xl font-semibold">Connector stampanti</h2><p className="text-sm text-neutral-600">Stato per la sede corrente, heartbeat, spool e diagnostica device.</p></div>
 {state.error&&<p className="border border-red-300 bg-red-50 p-2 text-sm text-red-800">{state.error}</p>}{state.message&&<p className="border border-emerald-300 bg-emerald-50 p-2 text-sm text-emerald-800">{state.message}</p>}{state.secret&&<output className="block whitespace-pre-wrap border border-amber-400 bg-amber-50 p-3 font-mono text-sm break-all">{state.secret}{state.expiresAt?`\nScade: ${state.expiresAt}`:""}</output>}
 <form action={action} className="flex flex-wrap items-end gap-2 border p-3"><label className="grid gap-1 text-sm">Stampante<select name="printerId" required className="border p-2"><option value="">Seleziona</option>{printers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button disabled={pending} name="operation" value="pair" className="inline-flex items-center gap-2 border px-3 py-2"><KeyRound size={16}/>Genera pairing</button><button disabled={pending} name="operation" value="test" className="inline-flex items-center gap-2 border px-3 py-2"><Printer size={16}/>Stampa test</button></form>
 <section className="border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-semibold">Catalogo FUSION</h3><p className="text-sm text-neutral-600">Nome e prezzo base sono controllati da FUSION; foto, descrizione commerciale, menu e routing restano controllati da Nexus.</p></div><form action={action}><button disabled={pending} name="operation" value="catalog-sync" className="inline-flex items-center gap-2 border px-3 py-2"><RefreshCw size={16}/>Sincronizza ora con FUSION</button></form></div>{catalog.length===0?<p className="mt-2 text-sm text-neutral-600">Nessuna sincronizzazione catalogo completata.</p>:catalog.map((s,index)=><div key={index} className="mt-2 text-sm"><strong>{s.status}</strong> · ultimo sync {s.lastSyncAt??"mai"} · PLU {s.totalCount} · creati {s.createdCount} · aggiornati {s.updatedCount} · invariati {s.unchangedCount} · mancanti {s.missingCount} · errori {s.errorCount}{s.lastError&&<p className="text-red-700">{s.lastError}</p>}</div>)}</section>
 <div className="grid gap-3">{devices.length===0&&<p className="text-sm text-neutral-600">Nessun connector associato.</p>}{devices.map(d=><article key={d.id} className="border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{d.name} · {d.printer.name}</strong><span className={d.online&&d.printerOnline?"text-emerald-700":"text-amber-700"}>{d.status} · {d.online?"heartbeat attivo":"offline"} · stampante {d.printerOnline?"online":"offline"}</span></div><p className="text-sm text-neutral-600">{d.printer.station.name} · credenziale {d.credentialPrefix}… · heartbeat {d.lastHeartbeatAt??"mai"}</p>{d.lastError&&<p className="mt-1 text-sm text-red-700">{d.lastError}</p>}{d.diagnostics!=null&&<details className="mt-2 text-sm"><summary>Diagnostica</summary><pre className="mt-1 overflow-auto border bg-neutral-50 p-2">{JSON.stringify(d.diagnostics,null,2)}</pre></details>}{d.status!=="REVOKED"&&<form action={action} className="mt-2 flex gap-2"><input type="hidden" name="deviceId" value={d.id}/><button disabled={pending} name="operation" value="rotate" className="inline-flex items-center gap-2 border px-2 py-1"><RefreshCw size={15}/>Ruota</button><button disabled={pending} name="operation" value="revoke" className="inline-flex items-center gap-2 border px-2 py-1 text-red-700"><Unplug size={15}/>Revoca</button></form>}</article>)}</div></section>;
}
